/* eslint-disable sonarjs/no-duplicate-string */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

import Asset from './asset';

export default function Model(properties) {
  const group = useRef();
  const { nodes } = useGLTF('/M-65-341_One_Story_Exhibit_Jonas.gltf');
  return (
    <group ref={group} {...properties} dispose={undefined}>
      <group position={[0, 0.92, -0.34]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Lampe' }}>
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
        <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
        <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
        <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
      </group>
      <group position={[0, 0.92, -0.06]} rotation={[-Math.PI / 2, 0, Math.PI]} userData={{ name: 'Korpus_Lampe_600' }}>
        <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
        <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
        <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
        <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
      </group>
      <group position={[0.18, 0.53, -0.49]} rotation={[-3.13, 0, -Math.PI]} userData={{ name: 'Behlter_400mm' }}>
        <group position={[0.23, 0.03, 0.25]} rotation={[0.02, 0, 0]} userData={{ name: 'PlexibehXE4lter_400er' }}>
          <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
          <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
          <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
          <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
          <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} />
          <mesh geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} />
          <mesh geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} />
          <mesh geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} />
          <mesh geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} />
        </group>
        <mesh
          geometry={nodes.Clamp50er_1.geometry}
          material={nodes.Clamp50er_1.material}
          position={[0.03, 0.43, 0.26]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'Clamp50er' }}
        />
      </group>
      <Asset
        position={[0.22, 1.76, -1.47]}
        rotation={[-Math.PI / 2, 0.02, 0]}
        userData={{ name: 'TrustSens _1 TM371' }}
        meshName={'TT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} />
        <mesh geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} />
        <mesh geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} />
      </Asset>
      <Asset
        position={[0.21, 1.61, -1.02]}
        rotation={[-Math.PI / 2, 0, 1.59]}
        userData={{ name: 'PMP71' }}
        meshName={'PT1005'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_30.geometry} material={nodes.mesh_30.material} />
        <mesh geometry={nodes.mesh_31.geometry} material={nodes.mesh_31.material} />
        <mesh geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} />
        <mesh geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} />
        <mesh geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} />
      </Asset>
      <Asset
        position={[0.21, 1.57, -1.25]}
        rotation={[Math.PI / 2, 1.54, -Math.PI / 2]}
        userData={{ name: 'Promag 400 5W4C25' }}
        meshName={'FT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} />
        <mesh geometry={nodes.mesh_36.geometry} material={nodes.mesh_36.material} />
        <mesh geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} />
        <mesh geometry={nodes.mesh_38.geometry} material={nodes.mesh_38.material} />
        <mesh geometry={nodes.mesh_39.geometry} material={nodes.mesh_39.material} />
      </Asset>
      <Asset
        position={[0.21, 1.19, -1.47]}
        rotation={[0, 0.03, 1.55]}
        userData={{ name: 'Promag 300 8F3B25' }}
        meshName={'FT1001'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_40.geometry} material={nodes.mesh_40.material} />
        <mesh geometry={nodes.mesh_41.geometry} material={nodes.mesh_41.material} />
        <mesh geometry={nodes.mesh_42.geometry} material={nodes.mesh_42.material} />
        <mesh geometry={nodes.mesh_43.geometry} material={nodes.mesh_43.material} />
        <mesh geometry={nodes.mesh_44.geometry} material={nodes.mesh_44.material} />
      </Asset>
      <Asset
        position={[0.17, 0.77, -0.75]}
        rotation={[-Math.PI / 2, 1.31, 0]}
        userData={{ name: 'CPA842' }}
        meshName={'QT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_45.geometry} material={nodes.mesh_45.material} />
        <mesh geometry={nodes.mesh_46.geometry} material={nodes.mesh_46.material} />
        <mesh geometry={nodes.mesh_47.geometry} material={nodes.mesh_47.material} />
      </Asset>
      <Asset
        position={[0.22, 0.64, -0.74]}
        rotation={[2.61, Math.PI / 2, 0]}
        userData={{ name: 'FMB50' }}
        meshName={'PT1003'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_48.geometry} material={nodes.mesh_48.material} />
        <mesh geometry={nodes.mesh_49.geometry} material={nodes.mesh_49.material} />
        <mesh geometry={nodes.mesh_50.geometry} material={nodes.mesh_50.material} />
        <mesh geometry={nodes.mesh_51.geometry} material={nodes.mesh_51.material} />
      </Asset>
      <Asset
        position={[0.26, 1.16, -0.74]}
        rotation={[-1.73, Math.PI / 2, 0]}
        userData={{ name: 'FTL33' }}
        meshName={'LT1004'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_52.geometry} material={nodes.mesh_52.material} />
        <mesh geometry={nodes.mesh_53.geometry} material={nodes.mesh_53.material} />
      </Asset>
      <Asset
        position={[0.28, 1.07, -0.74]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'PMP21' }}
        meshName={'PT1001'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_54.geometry} material={nodes.mesh_54.material} />
        <mesh geometry={nodes.mesh_55.geometry} material={nodes.mesh_55.material} />
        <mesh geometry={nodes.mesh_56.geometry} material={nodes.mesh_56.material} />
        <mesh geometry={nodes.mesh_57.geometry} material={nodes.mesh_57.material} />
      </Asset>
      <Asset
        position={[0.23, 0.97, -0.74]}
        rotation={[1.63, Math.PI / 2, 0]}
        userData={{ name: 'TM411' }}
        meshName={'TT1001'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_58.geometry} material={nodes.mesh_58.material} />
        <mesh geometry={nodes.mesh_59.geometry} material={nodes.mesh_59.material} />
        <mesh geometry={nodes.mesh_60.geometry} material={nodes.mesh_60.material} />
        <mesh geometry={nodes.mesh_61.geometry} material={nodes.mesh_61.material} />
        <mesh geometry={nodes.mesh_62.geometry} material={nodes.mesh_62.material} />
        <mesh geometry={nodes.mesh_63.geometry} material={nodes.mesh_63.material} />
      </Asset>
      <group position={[0.17, 0.84, -0.74]} rotation={[-Math.PI / 2, 1.31, 0]} userData={{ name: 'CPA842' }}>
        <mesh geometry={nodes.mesh_64.geometry} material={nodes.mesh_64.material} />
        <mesh geometry={nodes.mesh_65.geometry} material={nodes.mesh_65.material} />
        <mesh geometry={nodes.mesh_66.geometry} material={nodes.mesh_66.material} />
      </group>
      <group position={[-0.05, 0.73, -0.96]} rotation={[-2.88, 0, 3.13]} userData={{ name: 'CPA871' }}>
        <mesh geometry={nodes.mesh_67.geometry} material={nodes.mesh_67.material} />
        <mesh geometry={nodes.mesh_68.geometry} material={nodes.mesh_68.material} />
        <mesh geometry={nodes.mesh_69.geometry} material={nodes.mesh_69.material} />
      </group>
      <group position={[0.21, 0.8, -0.85]} rotation={[0, 1.57, 0]} userData={{ name: 'FXFClleitung_links_DN25' }}>
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)'].material}
          position={[0.17, -0.25, 0]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 16 25 x 33.7(1)' }}
        />
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_1'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_1'].material}
          position={[0.28, 0.77, 0]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 16 25 x 33.7(1)' }}
        />
        <mesh
          geometry={nodes.FXFClleitung_links_90Grad_DN25.geometry}
          material={nodes.FXFClleitung_links_90Grad_DN25.material}
          position={[0.17, -0.23, 0]}
          userData={{ name: 'FXFClleitung_links 90Grad_DN25' }}
        />
      </group>
      <group
        position={[0.21, 1.44, -1.47]}
        rotation={[-Math.PI / 2, -1.55, 0]}
        userData={{ name: 'FXFClleitung_rechts_Bogen_DN25' }}
      >
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_2'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_2'].material}
          position={[-0.03, 0, 0]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 16 25 x 33.7(1)' }}
        />
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_3'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_3'].material}
          position={[0.13, -0.13, 0]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 16 25 x 33.7(1)' }}
        />
        <mesh
          geometry={nodes.FXFClleitung_rechts_90Grad_DN25.geometry}
          material={nodes.FXFClleitung_rechts_90Grad_DN25.material}
          position={[-0.02, 0, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: 'FXFClleitung_rechts 90Grad_DN25' }}
        />
      </group>
      <group
        position={[0.2, 0.59, -1.46]}
        rotation={[-Math.PI / 2, -1.55, 0]}
        userData={{ name: 'FXFClleitung_rechts_gerade_DN25' }}
      >
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_4'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_4'].material}
          position={[-0.03, 0.01, 0]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 16 25 x 33.7(1)' }}
        />
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_5'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_16_25_x_337(1)_5'].material}
          position={[0.38, 0.01, 0]}
          rotation={[0, 0, Math.PI]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 16 25 x 33.7(1)' }}
        />
        <mesh
          geometry={nodes.FXFClleitung_links_DN25_1.geometry}
          material={nodes.FXFClleitung_links_DN25_1.material}
          position={[0.36, 0.01, 0]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'FXFClleitung_links_DN25_1' }}
        />
      </group>
      <Asset
        position={[-0.15, 1.29, -0.82]}
        rotation={[-Math.PI / 2, 0, -1.58]}
        userData={{ name: 'FMP56' }}
        meshName={'LT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_80.geometry} material={nodes.mesh_80.material} />
        <mesh geometry={nodes.mesh_81.geometry} material={nodes.mesh_81.material} />
        <mesh geometry={nodes.mesh_82.geometry} material={nodes.mesh_82.material} />
        <mesh geometry={nodes.mesh_83.geometry} material={nodes.mesh_83.material} />
        <mesh geometry={nodes.mesh_84.geometry} material={nodes.mesh_84.material} />
        <mesh geometry={nodes.mesh_85.geometry} material={nodes.mesh_85.material} />
      </Asset>
      <Asset
        position={[0.03, 1.28, -0.82]}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'FMR20' }}
        meshName={'LT1003'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_86.geometry} material={nodes.mesh_86.material} />
        <mesh geometry={nodes.mesh_87.geometry} material={nodes.mesh_87.material} />
        <mesh geometry={nodes.mesh_88.geometry} material={nodes.mesh_88.material} />
        <mesh geometry={nodes.mesh_89.geometry} material={nodes.mesh_89.material} />
      </Asset>
      <Asset
        position={[0.03, 1.37, -0.66]}
        rotation={[-Math.PI / 2, 0, 1.51]}
        userData={{ name: 'FMR62' }}
        meshName={'LT1001'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_90.geometry} material={nodes.mesh_90.material} />
        <mesh geometry={nodes.mesh_91.geometry} material={nodes.mesh_91.material} />
        <mesh geometry={nodes.mesh_92.geometry} material={nodes.mesh_92.material} />
        <mesh geometry={nodes.mesh_93.geometry} material={nodes.mesh_93.material} />
        <mesh geometry={nodes.mesh_94.geometry} material={nodes.mesh_94.material} />
        <mesh geometry={nodes.mesh_95.geometry} material={nodes.mesh_95.material} />
        <mesh geometry={nodes.mesh_96.geometry} material={nodes.mesh_96.material} />
      </Asset>
      <Asset
        position={[-0.15, 1.26, -0.66]}
        rotation={[-Math.PI / 2, 0, -1.58]}
        userData={{ name: 'FTM50' }}
        meshName={'LT1005'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_97.geometry} material={nodes.mesh_97.material} />
        <mesh geometry={nodes.mesh_98.geometry} material={nodes.mesh_98.material} />
        <mesh geometry={nodes.mesh_99.geometry} material={nodes.mesh_99.material} />
      </Asset>
      <Asset
        position={[-0.03, 0.58, -1.45]}
        rotation={[-0.33, 0, Math.PI]}
        userData={{ name: 'CM42' }}
        meshName={'QT1001'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_100.geometry} material={nodes.mesh_100.material} />
        <mesh geometry={nodes.mesh_101.geometry} material={nodes.mesh_101.material} />
        <mesh geometry={nodes.mesh_102.geometry} material={nodes.mesh_102.material} />
        <mesh geometry={nodes.mesh_103.geometry} material={nodes.mesh_103.material} />
        <mesh geometry={nodes.mesh_104.geometry} material={nodes.mesh_104.material} />
        <mesh geometry={nodes.mesh_105.geometry} material={nodes.mesh_105.material} />
        <mesh geometry={nodes.mesh_106.geometry} material={nodes.mesh_106.material} />
      </Asset>
      <Asset
        position={[-0.2, 0.8, -1.03]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'tmass150' }}
        meshName={'FT1005'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_108.geometry} material={nodes.mesh_108.material} />
        <mesh geometry={nodes.mesh_109.geometry} material={nodes.mesh_109.material} />
        <mesh geometry={nodes.mesh_110.geometry} material={nodes.mesh_110.material} />
        <mesh geometry={nodes.mesh_111.geometry} material={nodes.mesh_111.material} />
        <mesh geometry={nodes.mesh_112.geometry} material={nodes.mesh_112.material} />
        <mesh geometry={nodes.mesh_113.geometry} material={nodes.mesh_113.material} />
        <mesh geometry={nodes.mesh_114.geometry} material={nodes.mesh_114.material} />
        <mesh geometry={nodes.mesh_115.geometry} material={nodes.mesh_115.material} />
        <mesh geometry={nodes.mesh_116.geometry} material={nodes.mesh_116.material} />
        <mesh geometry={nodes.mesh_117.geometry} material={nodes.mesh_117.material} />
        <mesh geometry={nodes.mesh_118.geometry} material={nodes.mesh_118.material} />
        <mesh geometry={nodes.mesh_119.geometry} material={nodes.mesh_119.material} />
        <mesh geometry={nodes.mesh_120.geometry} material={nodes.mesh_120.material} />
        <mesh geometry={nodes.mesh_121.geometry} material={nodes.mesh_121.material} />
        <mesh geometry={nodes.mesh_122.geometry} material={nodes.mesh_122.material} />
      </Asset>
      <Asset
        position={[-0.2, 1.07, -1.03]}
        rotation={[-Math.PI, 0.01, -Math.PI / 2]}
        userData={{ name: 'Prosonic Floww B200 9B2B50' }}
        meshName={'FT1004'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_123.geometry} material={nodes.mesh_123.material} />
        <mesh geometry={nodes.mesh_124.geometry} material={nodes.mesh_124.material} />
        <mesh geometry={nodes.mesh_125.geometry} material={nodes.mesh_125.material} />
        <mesh geometry={nodes.mesh_126.geometry} material={nodes.mesh_126.material} />
        <mesh geometry={nodes.mesh_127.geometry} material={nodes.mesh_127.material} />
        <mesh geometry={nodes.mesh_128.geometry} material={nodes.mesh_128.material} />
        <mesh geometry={nodes.mesh_129.geometry} material={nodes.mesh_129.material} />
      </Asset>
      <Asset
        position={[-0.2, 1.52, -1.35]}
        rotation={[-Math.PI / 2, 0, -1.59]}
        userData={{ name: 'Promag 100 7F2C50' }}
        meshName={'FT1003'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_130.geometry} material={nodes.mesh_130.material} />
        <mesh geometry={nodes.mesh_131.geometry} material={nodes.mesh_131.material} />
        <mesh geometry={nodes.mesh_132.geometry} material={nodes.mesh_132.material} />
        <mesh geometry={nodes.mesh_133.geometry} material={nodes.mesh_133.material} />
        <mesh geometry={nodes.mesh_134.geometry} material={nodes.mesh_134.material} />
        <mesh geometry={nodes.mesh_135.geometry} material={nodes.mesh_135.material} />
        <mesh geometry={nodes.mesh_136.geometry} material={nodes.mesh_136.material} />
        <mesh geometry={nodes.mesh_137.geometry} material={nodes.mesh_137.material} />
        <mesh geometry={nodes.mesh_138.geometry} material={nodes.mesh_138.material} />
      </Asset>
      <group position={[-0.2, 1.41, -1.09]} rotation={[Math.PI, -1.55, Math.PI]} userData={{ name: 'DN50_Rohrbogen' }}>
        <mesh
          geometry={nodes.Rohrbogen_DN50_.geometry}
          material={nodes.Rohrbogen_DN50_.material}
          position={[0.06, -0.19, 0]}
          userData={{ name: 'Rohrbogen_DN50_' }}
        />
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_25_50_x_603'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_25_50_x_603'].material}
          position={[-0.16, 0.11, 0]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 25 50 x 60.3' }}
        />
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_25_50_x_603_1'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_25_50_x_603_1'].material}
          position={[0.06, -0.21, 0]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 25 50 x 60.3' }}
        />
      </group>
      <group
        position={[-0.19, 1.45, -1.61]}
        rotation={[-1.39, 1.48, 1.39]}
        userData={{ name: 'DN50_Rohrende_schrXE4g' }}
      >
        <group position={[-0.01, 0.07, 0]} rotation={[0, 0, 0]} userData={{ name: 'DN50_Rohrende_schrXE4g_1' }}>
          <mesh geometry={nodes.mesh_142.geometry} material={nodes.mesh_142.material} />
          <mesh geometry={nodes.mesh_143.geometry} material={nodes.mesh_143.material} />
        </group>
        <mesh
          geometry={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_25_50_x_603_2'].geometry}
          material={nodes['DIN_EN_1092-1_Flachflansch_fXFCr_SchweiXDFtyp_01_-_PN_25_50_x_603_2'].material}
          position={[-0.16, 0.07, 0]}
          rotation={[0.13, 0, 0]}
          userData={{ name: 'DIN EN 1092-1 Flachflansch fXFCr SchweiXDFtyp 01 - PN 25 50 x 60.3' }}
        />
      </group>
      <Asset
        position={[0.18, 0.82, -0.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'SWG70' }}
        meshName={'SWG70'}
        assetSelected={properties.assetSelected}
      >
        <group position={[0, 0.06, 0]} rotation={[0, -1.57, 0]} userData={{ name: 'DM_F2_DECKEL_MONTIERT_ASM' }}>
          <group
            position={[0.05, 0.01, 0.11]}
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: 'DM_F2_SCHRAUBE_SCHEIBE_M4X18_ASM' }}
          >
            <mesh
              geometry={nodes.DM_F2_SCHRAUBE_M4X18.geometry}
              material={nodes.DM_F2_SCHRAUBE_M4X18.material}
              userData={{ name: 'DM_F2_SCHRAUBE_M4X18' }}
            />
            <mesh
              geometry={nodes.DM_F2_SCHEIBE.geometry}
              material={nodes.DM_F2_SCHEIBE.material}
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              userData={{ name: 'DM_F2_SCHEIBE' }}
            />
          </group>
          <group
            position={[0.05, 0.01, -0.11]}
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: 'DM_F2_SCHRAUBE_SCHEIBE_M4X18_ASM' }}
          >
            <mesh
              geometry={nodes.DM_F2_SCHRAUBE_M4X18_1.geometry}
              material={nodes.DM_F2_SCHRAUBE_M4X18_1.material}
              userData={{ name: 'DM_F2_SCHRAUBE_M4X18' }}
            />
            <mesh
              geometry={nodes.DM_F2_SCHEIBE_1.geometry}
              material={nodes.DM_F2_SCHEIBE_1.material}
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              userData={{ name: 'DM_F2_SCHEIBE' }}
            />
          </group>
          <group
            position={[-0.05, 0.01, -0.11]}
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: 'DM_F2_SCHRAUBE_SCHEIBE_M4X18_ASM' }}
          >
            <mesh
              geometry={nodes.DM_F2_SCHRAUBE_M4X18_2.geometry}
              material={nodes.DM_F2_SCHRAUBE_M4X18_2.material}
              userData={{ name: 'DM_F2_SCHRAUBE_M4X18' }}
            />
            <mesh
              geometry={nodes.DM_F2_SCHEIBE_2.geometry}
              material={nodes.DM_F2_SCHEIBE_2.material}
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              userData={{ name: 'DM_F2_SCHEIBE' }}
            />
          </group>
          <group
            position={[-0.05, 0.01, 0.11]}
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: 'DM_F2_SCHRAUBE_SCHEIBE_M4X18_ASM' }}
          >
            <mesh
              geometry={nodes.DM_F2_SCHRAUBE_M4X18_3.geometry}
              material={nodes.DM_F2_SCHRAUBE_M4X18_3.material}
              userData={{ name: 'DM_F2_SCHRAUBE_M4X18' }}
            />
            <mesh
              geometry={nodes.DM_F2_SCHEIBE_3.geometry}
              material={nodes.DM_F2_SCHEIBE_3.material}
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              userData={{ name: 'DM_F2_SCHEIBE' }}
            />
          </group>
          <group
            position={[-0.03, 0, 0.1]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            userData={{ name: 'DM_F2_SCHRAUBE_SCHEIBE_M4X8_ASM' }}
          >
            <mesh
              geometry={nodes.DM_F2_SCHEIBE_4.geometry}
              material={nodes.DM_F2_SCHEIBE_4.material}
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              userData={{ name: 'DM_F2_SCHEIBE' }}
            />
            <mesh
              geometry={nodes.DM_F2_SCHRAUBE_M4X8.geometry}
              material={nodes.DM_F2_SCHRAUBE_M4X8.material}
              userData={{ name: 'DM_F2_SCHRAUBE_M4X8' }}
            />
          </group>
          <mesh
            geometry={nodes.DM_04AS70.geometry}
            material={nodes.DM_04AS70.material}
            userData={{ name: 'DM_04AS70' }}
          />
          <mesh
            geometry={nodes.DM_04AVP3.geometry}
            material={nodes.DM_04AVP3.material}
            position={[0, 0, 0]}
            rotation={[0, -1.57, 0]}
            userData={{ name: 'DM_04AVP3' }}
          />
        </group>
        <group position={[-0.09, 0.03, 0.06]} rotation={[1.56, Math.PI / 2, 0]} userData={{ name: 'ANTENNE' }}>
          <mesh geometry={nodes.mesh_163.geometry} material={nodes.mesh_163.material} />
          <mesh geometry={nodes.mesh_164.geometry} material={nodes.mesh_164.material} />
          <mesh geometry={nodes.mesh_165.geometry} material={nodes.mesh_165.material} />
          <mesh geometry={nodes.mesh_166.geometry} material={nodes.mesh_166.material} />
        </group>
        <mesh
          geometry={nodes.DM_WIRELESS.geometry}
          material={nodes.DM_WIRELESS.material}
          userData={{ name: 'DM_WIRELESS' }}
        />
        <mesh
          geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK'].geometry}
          material={nodes['DM_CABLE-GLAND-M16-EX-BLACK'].material}
          position={[0.09, 0.05, -0.08]}
          rotation={[0.01, 0, -Math.PI / 2]}
          userData={{ name: 'DM_CABLE-GLAND-M16-EX-BLACK' }}
        />
        <mesh
          geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK_1'].geometry}
          material={nodes['DM_CABLE-GLAND-M16-EX-BLACK_1'].material}
          position={[0.05, 0.05, -0.08]}
          rotation={[0.01, 0, -Math.PI / 2]}
          userData={{ name: 'DM_CABLE-GLAND-M16-EX-BLACK' }}
        />
        <mesh
          geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK_2'].geometry}
          material={nodes['DM_CABLE-GLAND-M16-EX-BLACK_2'].material}
          position={[0, 0.05, -0.08]}
          rotation={[0.01, 0, -Math.PI / 2]}
          userData={{ name: 'DM_CABLE-GLAND-M16-EX-BLACK' }}
        />
        <mesh
          geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK_3'].geometry}
          material={nodes['DM_CABLE-GLAND-M16-EX-BLACK_3'].material}
          position={[-0.05, 0.05, -0.08]}
          rotation={[0.01, 0, -Math.PI / 2]}
          userData={{ name: 'DM_CABLE-GLAND-M16-EX-BLACK' }}
        />
        <mesh
          geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK_4'].geometry}
          material={nodes['DM_CABLE-GLAND-M16-EX-BLACK_4'].material}
          position={[-0.09, 0.05, -0.08]}
          rotation={[0.01, 0, -Math.PI / 2]}
          userData={{ name: 'DM_CABLE-GLAND-M16-EX-BLACK' }}
        />
        <mesh
          geometry={nodes.ERDBUEGEL.geometry}
          material={nodes.ERDBUEGEL.material}
          position={[0.12, 0.01, -0.02]}
          rotation={[0, 1.57, 0]}
          userData={{ name: 'ERDBUEGEL' }}
        />
        <mesh
          geometry={nodes.FEDERSCHEIBE.geometry}
          material={nodes.FEDERSCHEIBE.material}
          position={[0.12, 0.02, -0.02]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: 'FEDERSCHEIBE' }}
        />
        <mesh
          geometry={nodes.SCHRAUBEERDKLEMME.geometry}
          material={nodes.SCHRAUBEERDKLEMME.material}
          position={[0.12, 0.02, -0.02]}
          userData={{ name: 'SCHRAUBEERDKLEMME' }}
        />
      </Asset>
      <Asset
        position={[0.2, 1.7, -0.94]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        userData={{ name: 'SWA70' }}
        meshName={'ADP_PT1005'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_170.geometry} material={nodes.mesh_170.material} />
        <mesh geometry={nodes.mesh_171.geometry} material={nodes.mesh_171.material} />
        <mesh geometry={nodes.mesh_172.geometry} material={nodes.mesh_172.material} />
      </Asset>
      <Asset
        position={[-0.16, 1.39, -0.9]}
        rotation={[-Math.PI / 2, 0, 3.13]}
        userData={{ name: 'SWA70' }}
        meshName={'ADP_LT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_173.geometry} material={nodes.mesh_173.material} />
        <mesh geometry={nodes.mesh_174.geometry} material={nodes.mesh_174.material} />
        <mesh geometry={nodes.mesh_175.geometry} material={nodes.mesh_175.material} />
      </Asset>
      <group
        position={[-0.25, 1.08, -1.49]}
        rotation={[1.62, -0.7, 1.64]}
        userData={{ name: 'FieldXpert (Getac 7110)' }}
      >
        <mesh geometry={nodes.mesh_178.geometry} material={nodes.mesh_178.material} />
        <mesh geometry={nodes.mesh_179.geometry} material={nodes.mesh_179.material} />
        <mesh geometry={nodes.mesh_180.geometry} material={nodes.mesh_180.material} />
        <mesh geometry={nodes.mesh_181.geometry} material={nodes.mesh_181.material} />
        <mesh geometry={nodes.mesh_182.geometry} material={nodes.mesh_182.material} />
        <mesh geometry={nodes.mesh_183.geometry} material={nodes.mesh_183.material} />
        <mesh geometry={nodes.mesh_184.geometry} material={nodes.mesh_184.material} />
        <mesh geometry={nodes.mesh_185.geometry} material={nodes.mesh_185.material} />
        <mesh geometry={nodes.mesh_186.geometry} material={nodes.mesh_186.material} />
        <mesh geometry={nodes.mesh_187.geometry} material={nodes.mesh_187.material} />
        <mesh geometry={nodes.mesh_188.geometry} material={nodes.mesh_188.material} />
        <mesh geometry={nodes.mesh_189.geometry} material={nodes.mesh_189.material} />
        <mesh geometry={nodes.mesh_190.geometry} material={nodes.mesh_190.material} />
        <mesh geometry={nodes.mesh_191.geometry} material={nodes.mesh_191.material} />
      </group>
      <group
        position={[0.28, 0.87, -0.74]}
        rotation={[-Math.PI / 2, 1.31, 0]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020' }}
      >
        <mesh geometry={nodes.mesh_192.geometry} material={nodes.mesh_192.material} />
        <mesh geometry={nodes.mesh_193.geometry} material={nodes.mesh_193.material} />
        <mesh geometry={nodes.mesh_194.geometry} material={nodes.mesh_194.material} />
      </group>
      <group
        position={[0.28, 0.79, -0.75]}
        rotation={[-Math.PI / 2, 1.31, 0]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020_1' }}
      >
        <mesh geometry={nodes.mesh_195.geometry} material={nodes.mesh_195.material} />
        <mesh geometry={nodes.mesh_196.geometry} material={nodes.mesh_196.material} />
        <mesh geometry={nodes.mesh_197.geometry} material={nodes.mesh_197.material} />
      </group>
      <group
        position={[0.3, 0.62, -1.25]}
        rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
        userData={{ name: 'RSG45-AA2AAAAAB1A1-Endress HauserConsultAG--10-15-2020' }}
      >
        <mesh geometry={nodes.mesh_198.geometry} material={nodes.mesh_198.material} />
        <mesh geometry={nodes.mesh_199.geometry} material={nodes.mesh_199.material} />
        <mesh geometry={nodes.mesh_200.geometry} material={nodes.mesh_200.material} />
      </group>
      <Asset
        position={[0.26, 0.79, -0.75]}
        rotation={[-Math.PI / 2, 1.31, 0]}
        userData={{ name: 'CM82' }}
        meshName={'QT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_201.geometry} material={nodes.mesh_201.material} />
        <mesh geometry={nodes.mesh_202.geometry} material={nodes.mesh_202.material} />
        <mesh geometry={nodes.mesh_203.geometry} material={nodes.mesh_203.material} />
      </Asset>
      <Asset
        position={[0.19, 0.88, 0.48]}
        rotation={[0, -0.03, Math.PI / 2]}
        userData={{ name: 'Promag 100 5H1B40' }}
        meshName={'FT1006'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_325.geometry} material={nodes.mesh_325.material} />
        <mesh geometry={nodes.mesh_326.geometry} material={nodes.mesh_326.material} />
        <mesh geometry={nodes.mesh_327.geometry} material={nodes.mesh_327.material} />
      </Asset>
      <Asset
        position={[0.19, 0.87, 0.26]}
        rotation={[0, -0.01, 2.56]}
        userData={{ name: 'PMP23' }}
        meshName={'PT1002'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_328.geometry} material={nodes.mesh_328.material} />
        <mesh geometry={nodes.mesh_329.geometry} material={nodes.mesh_329.material} />
        <mesh geometry={nodes.mesh_330.geometry} material={nodes.mesh_330.material} />
      </Asset>
      <group position={[0.24, 0.61, 1.02]} rotation={[0, 1.56, 0]} userData={{ name: 'Rohrbogen_41mm Rohr' }}>
        <group position={[0.89, -0.07, -0.05]} userData={{ name: 'Rohrbogen 41mm Rohr' }}>
          <mesh geometry={nodes.mesh_364.geometry} material={nodes.mesh_364.material} />
          <mesh geometry={nodes.mesh_365.geometry} material={nodes.mesh_365.material} />
          <mesh geometry={nodes.mesh_366.geometry} material={nodes.mesh_366.material} />
          <mesh geometry={nodes.mesh_367.geometry} material={nodes.mesh_367.material} />
        </group>
        <mesh
          geometry={nodes.Clamp50_41mm_Rohr.geometry}
          material={nodes.Clamp50_41mm_Rohr.material}
          position={[0.54, 0.41, -0.05]}
          rotation={[Math.PI, 0, 0]}
          userData={{ name: 'Clamp50_41mm_Rohr' }}
        />
        <mesh
          geometry={nodes.Clamp34_30mm_Rohr.geometry}
          material={nodes.Clamp34_30mm_Rohr.material}
          position={[0.89, 0.26, -0.05]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'Clamp34_30mm_Rohr' }}
        />
      </group>
      <group
        position={[-0.17, 0.88, 0.31]}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020_3' }}
      >
        <mesh geometry={nodes.mesh_369.geometry} material={nodes.mesh_369.material} />
        <mesh geometry={nodes.mesh_370.geometry} material={nodes.mesh_370.material} />
        <mesh geometry={nodes.mesh_371.geometry} material={nodes.mesh_371.material} />
      </group>
      <Asset
        position={[-0.11, 0.93, 0.25]}
        rotation={[-Math.PI / 2, 0, 1.52]}
        userData={{ name: 'TM131-AABHBAB2HA5BFEB3CA2DA1-Endress HauserConsultAG--10-19-2020' }}
        meshName={'DO - Tank'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_372.geometry} material={nodes.mesh_372.material} />
        <mesh geometry={nodes.mesh_373.geometry} material={nodes.mesh_373.material} />
        <mesh geometry={nodes.mesh_374.geometry} material={nodes.mesh_374.material} />
        <mesh geometry={nodes.mesh_375.geometry} material={nodes.mesh_375.material} />
      </Asset>
      <group
        position={[-0.17, 0.88, 0.19]}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020_4' }}
      >
        <mesh geometry={nodes.mesh_376.geometry} material={nodes.mesh_376.material} />
        <mesh geometry={nodes.mesh_377.geometry} material={nodes.mesh_377.material} />
        <mesh geometry={nodes.mesh_378.geometry} material={nodes.mesh_378.material} />
      </group>
      <Asset
        position={[-0.04, 1.01, 0.64]}
        rotation={[-2.27, 0, 0]}
        userData={{ name: 'CM44P' }}
        meshName={'Smart System Liquiline'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_380.geometry} material={nodes.mesh_380.material} />
        <mesh geometry={nodes.mesh_381.geometry} material={nodes.mesh_381.material} />
        <mesh geometry={nodes.mesh_382.geometry} material={nodes.mesh_382.material} />
        <mesh geometry={nodes.mesh_383.geometry} material={nodes.mesh_383.material} />
        <mesh geometry={nodes.mesh_384.geometry} material={nodes.mesh_384.material} />
      </Asset>
      <Asset
        position={[0.19, 1.19, 0.13]}
        rotation={[0, 0, 0]}
        userData={{ name: 'tm311_AAC1AA0ABC1B1' }}
        meshName={'TT1004'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_389.geometry} material={nodes.mesh_389.material} />
        <mesh geometry={nodes.mesh_390.geometry} material={nodes.mesh_390.material} />
        <mesh geometry={nodes.mesh_391.geometry} material={nodes.mesh_391.material} />
        <mesh geometry={nodes.mesh_392.geometry} material={nodes.mesh_392.material} />
        <mesh geometry={nodes.mesh_393.geometry} material={nodes.mesh_393.material} />
        <mesh geometry={nodes.mesh_394.geometry} material={nodes.mesh_394.material} />
      </Asset>
      <group
        position={[0.22, 1.09, -0.2]}
        rotation={[-1.57, -Math.PI / 4, 1.57]}
        userData={{ name: 'Bildschrim_22Zoll' }}
      >
        <mesh geometry={nodes.mesh_395.geometry} material={nodes.mesh_395.material} />
        <mesh geometry={nodes.mesh_396.geometry} material={nodes.mesh_396.material} />
      </group>
      <group
        position={[-0.23, 1.07, -0.18]}
        rotation={[-1.57, Math.PI / 4, -1.57]}
        userData={{ name: 'Bildschrim_22Zoll' }}
      >
        <mesh geometry={nodes.mesh_397.geometry} material={nodes.mesh_397.material} />
        <mesh geometry={nodes.mesh_398.geometry} material={nodes.mesh_398.material} />
      </group>
      <Asset
        position={[-0.25, 0.55, -1.36]}
        rotation={[-Math.PI, 1.57, 0]}
        userData={{ name: 'FWR30-AA1A1B7B0-Endress HauserConsultAG--10-22-2020' }}
        meshName={'IIoT Radar FWR 30'}
        assetSelected={properties.assetSelected}
      >
        <mesh geometry={nodes.mesh_399.geometry} material={nodes.mesh_399.material} />
        <mesh geometry={nodes.mesh_400.geometry} material={nodes.mesh_400.material} />
        <mesh geometry={nodes.mesh_401.geometry} material={nodes.mesh_401.material} />
        <mesh geometry={nodes.mesh_402.geometry} material={nodes.mesh_402.material} />
        <mesh geometry={nodes.mesh_403.geometry} material={nodes.mesh_403.material} />
        <mesh geometry={nodes.mesh_404.geometry} material={nodes.mesh_404.material} />
        <mesh geometry={nodes.mesh_405.geometry} material={nodes.mesh_405.material} />
      </Asset>
      <group position={[0.12, 0.66, 0.33]} rotation={[-Math.PI / 2, 0, -1.54]} userData={{ name: 'CYA680' }}>
        <mesh
          geometry={nodes.Clamp50er_2.geometry}
          material={nodes.Clamp50er_2.material}
          position={[0.15, 0.07, 0.08]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: 'Clamp50er' }}
        />
        <mesh
          geometry={nodes.Clamp50er_3.geometry}
          material={nodes.Clamp50er_3.material}
          position={[0.15, 0.07, 0.03]}
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: 'Clamp50er' }}
        />
        <mesh
          geometry={nodes.CYA680_1.geometry}
          material={nodes.CYA680_1.material}
          position={[0.15, 0.07, 0.05]}
          rotation={[0, 0, 0]}
          userData={{ name: 'CYA680_1' }}
        />
      </group>
      <group position={[0.27, 0.55, 0.63]} rotation={[-Math.PI / 2, 0, 1.6]} userData={{ name: 'OUA260' }}>
        <mesh
          geometry={nodes.Clamp50er_4.geometry}
          material={nodes.Clamp50er_4.material}
          position={[0.16, 0.08, 0.08]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: 'Clamp50er' }}
        />
        <mesh
          geometry={nodes.Clamp50er_5.geometry}
          material={nodes.Clamp50er_5.material}
          position={[0.16, 0.08, 0.03]}
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: 'Clamp50er' }}
        />
        <mesh
          geometry={nodes.OUA260_1.geometry}
          material={nodes.OUA260_1.material}
          position={[0.16, 0.08, 0.06]}
          rotation={[0, 0, 0]}
          userData={{ name: 'OUA260_1' }}
        />
      </group>
      <group
        position={[-0.05, 0.75, -1.01]}
        rotation={[-2.88, 0, 0]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020_2' }}
      >
        <mesh geometry={nodes.mesh_412.geometry} material={nodes.mesh_412.material} />
        <mesh geometry={nodes.mesh_413.geometry} material={nodes.mesh_413.material} />
        <mesh geometry={nodes.mesh_414.geometry} material={nodes.mesh_414.material} />
      </group>
      <group
        position={[0.2, 0.72, 0.66]}
        rotation={[0, 0.03, -0.03]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020_3' }}
      >
        <mesh geometry={nodes.mesh_416.geometry} material={nodes.mesh_416.material} />
        <mesh geometry={nodes.mesh_417.geometry} material={nodes.mesh_417.material} />
        <mesh geometry={nodes.mesh_418.geometry} material={nodes.mesh_418.material} />
      </group>
      <group
        position={[0.19, 0.72, 0.3]}
        rotation={[-Math.PI, -0.03, -0.03]}
        userData={{ name: 'CPS11D-7AA21-Endress HauserConsultAG--10-15-2020_4' }}
      >
        <mesh geometry={nodes.mesh_419.geometry} material={nodes.mesh_419.material} />
        <mesh geometry={nodes.mesh_420.geometry} material={nodes.mesh_420.material} />
        <mesh geometry={nodes.mesh_421.geometry} material={nodes.mesh_421.material} />
      </group>
      <mesh
        geometry={nodes.Korpus.geometry}
        material={nodes.Korpus.material}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'Korpus' }}
      />
      <mesh
        geometry={nodes.Halterung_ACER_27zoll.geometry}
        material={nodes.Halterung_ACER_27zoll.material}
        position={[0.15, 0.92, -0.2]}
        rotation={[-Math.PI / 2, 0, -1.57]}
        userData={{ name: 'Halterung_ACER_27zoll' }}
      />
      <mesh
        geometry={nodes.Halterung_ACER_27zoll_1.geometry}
        material={nodes.Halterung_ACER_27zoll_1.material}
        position={[-0.15, 0.92, -0.2]}
        rotation={[-Math.PI / 2, 0, 1.57]}
        userData={{ name: 'Halterung_ACER_27zoll' }}
      />
      <mesh
        geometry={nodes.One_Story_Exhibit_Beistellsockel.geometry}
        material={nodes.One_Story_Exhibit_Beistellsockel.material}
        position={[0, 0.02, 0.35]}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'One Story Exhibit Beistellsockel' }}
      />
      <mesh
        geometry={nodes.Schild.geometry}
        material={nodes.Schild.material}
        position={[0, 2.01, -0.44]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'Schild' }}
      />
      <mesh
        geometry={nodes.Schild_kurz.geometry}
        material={nodes.Schild_kurz.material}
        position={[0.01, 2.01, 0.04]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'Schild_kurz' }}
      />
      <mesh
        geometry={nodes.Plexideckel_400mm.geometry}
        material={nodes.Plexideckel_400mm.material}
        position={[-0.05, 1.24, -0.74]}
        rotation={[0, 1.56, 0]}
        userData={{ name: 'Plexideckel_400mm' }}
      />
      <mesh
        geometry={nodes.RSG45_Halter.geometry}
        material={nodes.RSG45_Halter.material}
        position={[0.32, 0.55, -1.14]}
        userData={{ name: 'RSG45_Halter' }}
      />
      <mesh
        geometry={nodes.CM42_SchrXE4ge.geometry}
        material={nodes.CM42_SchrXE4ge.material}
        position={[0.04, 0.55, -1.38]}
        rotation={[0, 1.57, 0]}
        userData={{ name: 'CM42_SchrXE4ge' }}
      />
      <mesh
        geometry={nodes.Halter_Tablet.geometry}
        material={nodes.Halter_Tablet.material}
        position={[-0.25, 0.55, -1.48]}
        rotation={[-Math.PI / 2, 0, 1.52]}
        userData={{ name: 'Halter Tablet' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45'].geometry}
        material={nodes['DIN_933_-_M12__x_45'].material}
        position={[0.24, 0.57, -1.05]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_1'].geometry}
        material={nodes['DIN_933_-_M12__x_45_1'].material}
        position={[0.18, 0.57, -1.05]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_2'].geometry}
        material={nodes['DIN_933_-_M12__x_45_2'].material}
        position={[0.18, 0.57, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_3'].geometry}
        material={nodes['DIN_933_-_M12__x_45_3'].material}
        position={[0.24, 0.57, -0.99]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_4'].geometry}
        material={nodes['DIN_933_-_M12__x_45_4'].material}
        position={[0.23, 0.58, -1.5]}
        rotation={[Math.PI / 2, 1.55, -Math.PI]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_5'].geometry}
        material={nodes['DIN_933_-_M12__x_45_5'].material}
        position={[0.17, 0.58, -1.5]}
        rotation={[-Math.PI, 0, 1.59]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_6'].geometry}
        material={nodes['DIN_933_-_M12__x_45_6'].material}
        position={[0.17, 0.58, -1.44]}
        rotation={[-Math.PI / 2, -1.55, -Math.PI]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_45_7'].geometry}
        material={nodes['DIN_933_-_M12__x_45_7'].material}
        position={[0.23, 0.58, -1.44]}
        rotation={[0, 0, -1.59]}
        userData={{ name: 'DIN 933 - M12  x 45' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13'].geometry}
        material={nodes['DIN_125_-_A_13'].material}
        position={[0.24, 0.57, -1.05]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_1'].geometry}
        material={nodes['DIN_125_-_A_13_1'].material}
        position={[0.18, 0.57, -1.05]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_2'].geometry}
        material={nodes['DIN_125_-_A_13_2'].material}
        position={[0.18, 0.57, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_3'].geometry}
        material={nodes['DIN_125_-_A_13_3'].material}
        position={[0.24, 0.57, -0.99]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_4'].geometry}
        material={nodes['DIN_125_-_A_13_4'].material}
        position={[0.23, 0.58, -1.5]}
        rotation={[Math.PI / 2, 1.55, -Math.PI]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_5'].geometry}
        material={nodes['DIN_125_-_A_13_5'].material}
        position={[0.17, 0.58, -1.5]}
        rotation={[-Math.PI, 0, 1.59]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_6'].geometry}
        material={nodes['DIN_125_-_A_13_6'].material}
        position={[0.17, 0.58, -1.44]}
        rotation={[-Math.PI / 2, -1.55, -Math.PI]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_7'].geometry}
        material={nodes['DIN_125_-_A_13_7'].material}
        position={[0.23, 0.58, -1.44]}
        rotation={[0, 0, -1.59]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_8'].geometry}
        material={nodes['DIN_125_-_A_13_8'].material}
        position={[0.24, 1.42, -1.5]}
        rotation={[Math.PI / 2, 1.55, -Math.PI]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_9'].geometry}
        material={nodes['DIN_125_-_A_13_9'].material}
        position={[0.24, 1.38, -1.5]}
        rotation={[-Math.PI / 2, -1.55, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_10'].geometry}
        material={nodes['DIN_125_-_A_13_10'].material}
        position={[0.18, 1.42, -1.5]}
        rotation={[-Math.PI, 0, 1.59]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_11'].geometry}
        material={nodes['DIN_125_-_A_13_11'].material}
        position={[0.18, 1.39, -1.5]}
        rotation={[0, 0, 1.55]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_12'].geometry}
        material={nodes['DIN_125_-_A_13_12'].material}
        position={[0.18, 1.42, -1.44]}
        rotation={[-Math.PI / 2, -1.55, -Math.PI]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_13'].geometry}
        material={nodes['DIN_125_-_A_13_13'].material}
        position={[0.18, 1.39, -1.44]}
        rotation={[Math.PI / 2, 1.55, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_14'].geometry}
        material={nodes['DIN_125_-_A_13_14'].material}
        position={[0.24, 1.42, -1.44]}
        rotation={[0, 0, -1.59]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_15'].geometry}
        material={nodes['DIN_125_-_A_13_15'].material}
        position={[0.24, 1.38, -1.44]}
        rotation={[-Math.PI, 0, -1.55]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_16'].geometry}
        material={nodes['DIN_125_-_A_13_16'].material}
        position={[0.23, 0.99, -1.5]}
        rotation={[Math.PI / 2, 1.55, -Math.PI]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_17'].geometry}
        material={nodes['DIN_125_-_A_13_17'].material}
        position={[0.23, 0.95, -1.5]}
        rotation={[-Math.PI / 2, -1.55, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_18'].geometry}
        material={nodes['DIN_125_-_A_13_18'].material}
        position={[0.23, 0.99, -1.44]}
        rotation={[0, 0, -1.59]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_19'].geometry}
        material={nodes['DIN_125_-_A_13_19'].material}
        position={[0.23, 0.95, -1.44]}
        rotation={[-Math.PI, 0, -1.55]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_20'].geometry}
        material={nodes['DIN_125_-_A_13_20'].material}
        position={[0.17, 0.99, -1.44]}
        rotation={[-Math.PI / 2, -1.55, -Math.PI]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_21'].geometry}
        material={nodes['DIN_125_-_A_13_21'].material}
        position={[0.17, 0.95, -1.44]}
        rotation={[Math.PI / 2, 1.55, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_22'].geometry}
        material={nodes['DIN_125_-_A_13_22'].material}
        position={[0.17, 0.99, -1.5]}
        rotation={[-Math.PI, 0, 1.59]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_23'].geometry}
        material={nodes['DIN_125_-_A_13_23'].material}
        position={[0.17, 0.95, -1.5]}
        rotation={[0, 0, 1.55]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_24'].geometry}
        material={nodes['DIN_125_-_A_13_24'].material}
        position={[0.24, 1.54, -1.37]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_25'].geometry}
        material={nodes['DIN_125_-_A_13_25'].material}
        position={[0.24, 1.54, -1.33]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_26'].geometry}
        material={nodes['DIN_125_-_A_13_26'].material}
        position={[0.18, 1.54, -1.37]}
        rotation={[-Math.PI, 1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_27'].geometry}
        material={nodes['DIN_125_-_A_13_27'].material}
        position={[0.18, 1.54, -1.33]}
        rotation={[0, 1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_28'].geometry}
        material={nodes['DIN_125_-_A_13_28'].material}
        position={[0.18, 1.6, -1.37]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_29'].geometry}
        material={nodes['DIN_125_-_A_13_29'].material}
        position={[0.18, 1.6, -1.33]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_30'].geometry}
        material={nodes['DIN_125_-_A_13_30'].material}
        position={[0.24, 1.6, -1.37]}
        rotation={[0, -1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_31'].geometry}
        material={nodes['DIN_125_-_A_13_31'].material}
        position={[0.24, 1.6, -1.33]}
        rotation={[Math.PI, -1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_32'].geometry}
        material={nodes['DIN_125_-_A_13_32'].material}
        position={[0.24, 1.54, -1.13]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_33'].geometry}
        material={nodes['DIN_125_-_A_13_33'].material}
        position={[0.24, 1.54, -1.17]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_34'].geometry}
        material={nodes['DIN_125_-_A_13_34'].material}
        position={[0.24, 1.6, -1.13]}
        rotation={[-Math.PI, -1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_35'].geometry}
        material={nodes['DIN_125_-_A_13_35'].material}
        position={[0.24, 1.6, -1.17]}
        rotation={[0, -1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_36'].geometry}
        material={nodes['DIN_125_-_A_13_36'].material}
        position={[0.18, 1.6, -1.13]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_37'].geometry}
        material={nodes['DIN_125_-_A_13_37'].material}
        position={[0.18, 1.6, -1.17]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_38'].geometry}
        material={nodes['DIN_125_-_A_13_38'].material}
        position={[0.18, 1.54, -1.13]}
        rotation={[0, 1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_13_39'].geometry}
        material={nodes['DIN_125_-_A_13_39'].material}
        position={[0.18, 1.54, -1.17]}
        rotation={[-Math.PI, 1.57, 0]}
        userData={{ name: 'DIN 125 - A 13' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55'].geometry}
        material={nodes['DIN_933_-_M12__x_55'].material}
        position={[0.24, 1.42, -1.5]}
        rotation={[Math.PI / 2, 1.55, -Math.PI]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_1'].geometry}
        material={nodes['DIN_933_-_M12__x_55_1'].material}
        position={[0.18, 1.42, -1.5]}
        rotation={[-Math.PI, 0, 1.59]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_2'].geometry}
        material={nodes['DIN_933_-_M12__x_55_2'].material}
        position={[0.18, 1.42, -1.44]}
        rotation={[-Math.PI / 2, -1.55, -Math.PI]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_3'].geometry}
        material={nodes['DIN_933_-_M12__x_55_3'].material}
        position={[0.24, 1.42, -1.44]}
        rotation={[0, 0, -1.59]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_4'].geometry}
        material={nodes['DIN_933_-_M12__x_55_4'].material}
        position={[0.23, 0.95, -1.5]}
        rotation={[-Math.PI / 2, -1.55, 0]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_5'].geometry}
        material={nodes['DIN_933_-_M12__x_55_5'].material}
        position={[0.23, 0.95, -1.44]}
        rotation={[-Math.PI, 0, -1.55]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_6'].geometry}
        material={nodes['DIN_933_-_M12__x_55_6'].material}
        position={[0.17, 0.95, -1.44]}
        rotation={[Math.PI / 2, 1.55, 0]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_7'].geometry}
        material={nodes['DIN_933_-_M12__x_55_7'].material}
        position={[0.17, 0.95, -1.5]}
        rotation={[0, 0, 1.55]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_8'].geometry}
        material={nodes['DIN_933_-_M12__x_55_8'].material}
        position={[0.24, 1.54, -1.37]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_9'].geometry}
        material={nodes['DIN_933_-_M12__x_55_9'].material}
        position={[0.18, 1.54, -1.37]}
        rotation={[-Math.PI, 1.57, 0]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_10'].geometry}
        material={nodes['DIN_933_-_M12__x_55_10'].material}
        position={[0.18, 1.6, -1.37]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_11'].geometry}
        material={nodes['DIN_933_-_M12__x_55_11'].material}
        position={[0.24, 1.6, -1.37]}
        rotation={[0, -1.57, 0]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_12'].geometry}
        material={nodes['DIN_933_-_M12__x_55_12'].material}
        position={[0.24, 1.54, -1.13]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_13'].geometry}
        material={nodes['DIN_933_-_M12__x_55_13'].material}
        position={[0.24, 1.6, -1.13]}
        rotation={[-Math.PI, -1.57, 0]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_14'].geometry}
        material={nodes['DIN_933_-_M12__x_55_14'].material}
        position={[0.18, 1.6, -1.13]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M12__x_55_15'].geometry}
        material={nodes['DIN_933_-_M12__x_55_15'].material}
        position={[0.18, 1.54, -1.13]}
        rotation={[0, 1.57, 0]}
        userData={{ name: 'DIN 933 - M12  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5'].material}
        position={[0.24, 1.37, -1.5]}
        rotation={[-Math.PI / 2, -1.55, 0]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_1'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_1'].material}
        position={[0.18, 1.38, -1.5]}
        rotation={[0, 0, 1.55]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_2'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_2'].material}
        position={[0.18, 1.38, -1.44]}
        rotation={[Math.PI / 2, 1.55, 0]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_3'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_3'].material}
        position={[0.24, 1.37, -1.44]}
        rotation={[-Math.PI, 0, -1.55]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_4'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_4'].material}
        position={[0.23, 1, -1.5]}
        rotation={[Math.PI / 2, 1.55, -Math.PI]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_5'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_5'].material}
        position={[0.23, 1, -1.44]}
        rotation={[0, 0, -1.59]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_6'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_6'].material}
        position={[0.17, 1, -1.44]}
        rotation={[-Math.PI / 2, -1.55, -Math.PI]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_7'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_7'].material}
        position={[0.17, 1, -1.5]}
        rotation={[-Math.PI, 0, 1.59]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_8'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_8'].material}
        position={[0.24, 1.54, -1.32]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_9'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_9'].material}
        position={[0.18, 1.54, -1.32]}
        rotation={[0, 1.57, 0]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_10'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_10'].material}
        position={[0.18, 1.6, -1.32]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_11'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_11'].material}
        position={[0.24, 1.6, -1.32]}
        rotation={[Math.PI, -1.57, 0]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_12'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_12'].material}
        position={[0.24, 1.54, -1.18]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_13'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_13'].material}
        position={[0.24, 1.6, -1.18]}
        rotation={[0, -1.57, 0]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_14'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_14'].material}
        position={[0.18, 1.6, -1.18]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M12_x_1,5_15'].geometry}
        material={nodes['DIN_934_-_M12_x_1,5_15'].material}
        position={[0.18, 1.54, -1.18]}
        rotation={[-Math.PI, 1.57, 0]}
        userData={{ name: 'DIN 934 - M12 x 1,5' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55'].geometry}
        material={nodes['DIN_933_-_M16__x_55'].material}
        position={[-0.25, 0.58, -1.08]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_1'].geometry}
        material={nodes['DIN_933_-_M16__x_55_1'].material}
        position={[-0.25, 0.93, -1.08]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_2'].geometry}
        material={nodes['DIN_933_-_M16__x_55_2'].material}
        position={[-0.25, 1.22, -1.08]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_3'].geometry}
        material={nodes['DIN_933_-_M16__x_55_3'].material}
        position={[-0.25, 0.58, -0.99]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_4'].geometry}
        material={nodes['DIN_933_-_M16__x_55_4'].material}
        position={[-0.25, 0.93, -0.99]}
        rotation={[0, 0, Math.PI / 2]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_5'].geometry}
        material={nodes['DIN_933_-_M16__x_55_5'].material}
        position={[-0.25, 1.22, -0.99]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_6'].geometry}
        material={nodes['DIN_933_-_M16__x_55_6'].material}
        position={[-0.16, 0.58, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_7'].geometry}
        material={nodes['DIN_933_-_M16__x_55_7'].material}
        position={[-0.16, 0.93, -0.99]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_8'].geometry}
        material={nodes['DIN_933_-_M16__x_55_8'].material}
        position={[-0.16, 1.22, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_9'].geometry}
        material={nodes['DIN_933_-_M16__x_55_9'].material}
        position={[-0.16, 0.58, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_10'].geometry}
        material={nodes['DIN_933_-_M16__x_55_10'].material}
        position={[-0.16, 0.93, -1.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_11'].geometry}
        material={nodes['DIN_933_-_M16__x_55_11'].material}
        position={[-0.16, 1.22, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_12'].geometry}
        material={nodes['DIN_933_-_M16__x_55_12'].material}
        position={[-0.24, 1.56, -1.23]}
        rotation={[-Math.PI / 2, 0, 1.55]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_13'].geometry}
        material={nodes['DIN_933_-_M16__x_55_13'].material}
        position={[-0.24, 1.56, -1.48]}
        rotation={[-1.57, 0, -1.59]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_14'].geometry}
        material={nodes['DIN_933_-_M16__x_55_14'].material}
        position={[-0.16, 1.56, -1.23]}
        rotation={[0, 1.55, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_15'].geometry}
        material={nodes['DIN_933_-_M16__x_55_15'].material}
        position={[-0.15, 1.56, -1.47]}
        rotation={[0, 1.55, 3.14]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_16'].geometry}
        material={nodes['DIN_933_-_M16__x_55_16'].material}
        position={[-0.16, 1.47, -1.23]}
        rotation={[1.57, 0, -1.55]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_17'].geometry}
        material={nodes['DIN_933_-_M16__x_55_17'].material}
        position={[-0.16, 1.47, -1.47]}
        rotation={[1.57, 0, 1.59]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_18'].geometry}
        material={nodes['DIN_933_-_M16__x_55_18'].material}
        position={[-0.25, 1.48, -1.23]}
        rotation={[-Math.PI, -1.55, 0]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_933_-_M16__x_55_19'].geometry}
        material={nodes['DIN_933_-_M16__x_55_19'].material}
        position={[-0.24, 1.48, -1.48]}
        rotation={[Math.PI, -1.55, -3.14]}
        userData={{ name: 'DIN 933 - M16  x 55' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17'].geometry}
        material={nodes['DIN_125_-_A_17'].material}
        position={[-0.25, 0.58, -1.08]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_1'].geometry}
        material={nodes['DIN_125_-_A_17_1'].material}
        position={[-0.25, 0.97, -1.08]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_2'].geometry}
        material={nodes['DIN_125_-_A_17_2'].material}
        position={[-0.25, 0.93, -1.08]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_3'].geometry}
        material={nodes['DIN_125_-_A_17_3'].material}
        position={[-0.25, 1.18, -1.08]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_4'].geometry}
        material={nodes['DIN_125_-_A_17_4'].material}
        position={[-0.25, 1.22, -1.08]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_5'].geometry}
        material={nodes['DIN_125_-_A_17_5'].material}
        position={[-0.25, 0.58, -0.99]}
        rotation={[0, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_6'].geometry}
        material={nodes['DIN_125_-_A_17_6'].material}
        position={[-0.25, 0.97, -0.99]}
        rotation={[0, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_7'].geometry}
        material={nodes['DIN_125_-_A_17_7'].material}
        position={[-0.25, 0.93, -0.99]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_8'].geometry}
        material={nodes['DIN_125_-_A_17_8'].material}
        position={[-0.25, 1.18, -0.99]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_9'].geometry}
        material={nodes['DIN_125_-_A_17_9'].material}
        position={[-0.25, 1.22, -0.99]}
        rotation={[0, 0, Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_10'].geometry}
        material={nodes['DIN_125_-_A_17_10'].material}
        position={[-0.16, 0.58, -0.99]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_11'].geometry}
        material={nodes['DIN_125_-_A_17_11'].material}
        position={[-0.16, 0.97, -0.99]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_12'].geometry}
        material={nodes['DIN_125_-_A_17_12'].material}
        position={[-0.16, 0.93, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_13'].geometry}
        material={nodes['DIN_125_-_A_17_13'].material}
        position={[-0.16, 1.18, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_14'].geometry}
        material={nodes['DIN_125_-_A_17_14'].material}
        position={[-0.16, 1.22, -0.99]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_15'].geometry}
        material={nodes['DIN_125_-_A_17_15'].material}
        position={[-0.16, 0.58, -1.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_16'].geometry}
        material={nodes['DIN_125_-_A_17_16'].material}
        position={[-0.16, 0.97, -1.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_17'].geometry}
        material={nodes['DIN_125_-_A_17_17'].material}
        position={[-0.16, 0.93, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_18'].geometry}
        material={nodes['DIN_125_-_A_17_18'].material}
        position={[-0.16, 1.18, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_19'].geometry}
        material={nodes['DIN_125_-_A_17_19'].material}
        position={[-0.16, 1.22, -1.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_20'].geometry}
        material={nodes['DIN_125_-_A_17_20'].material}
        position={[-0.24, 1.56, -1.24]}
        rotation={[-Math.PI / 2, 0, -1.59]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_21'].geometry}
        material={nodes['DIN_125_-_A_17_21'].material}
        position={[-0.24, 1.56, -1.27]}
        rotation={[-Math.PI / 2, 0, 1.55]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_22'].geometry}
        material={nodes['DIN_125_-_A_17_22'].material}
        position={[-0.24, 1.56, -1.43]}
        rotation={[Math.PI / 2, 0, 1.59]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_23'].geometry}
        material={nodes['DIN_125_-_A_17_23'].material}
        position={[-0.24, 1.56, -1.47]}
        rotation={[-1.54, 1.02, 1.54]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_24'].geometry}
        material={nodes['DIN_125_-_A_17_24'].material}
        position={[-0.16, 1.56, -1.23]}
        rotation={[0, 1.55, -3.14]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_25'].geometry}
        material={nodes['DIN_125_-_A_17_25'].material}
        position={[-0.16, 1.56, -1.27]}
        rotation={[0, 1.55, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_26'].geometry}
        material={nodes['DIN_125_-_A_17_26'].material}
        position={[-0.15, 1.56, -1.43]}
        rotation={[Math.PI, -1.55, 3.14]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_27'].geometry}
        material={nodes['DIN_125_-_A_17_27'].material}
        position={[-0.15, 1.56, -1.47]}
        rotation={[1.56, 0.55, -1.55]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_28'].geometry}
        material={nodes['DIN_125_-_A_17_28'].material}
        position={[-0.16, 1.47, -1.23]}
        rotation={[1.57, 0, 1.59]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_29'].geometry}
        material={nodes['DIN_125_-_A_17_29'].material}
        position={[-0.16, 1.47, -1.27]}
        rotation={[1.57, 0, -1.55]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_30'].geometry}
        material={nodes['DIN_125_-_A_17_30'].material}
        position={[-0.16, 1.47, -1.43]}
        rotation={[-1.57, 0, -1.59]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_31'].geometry}
        material={nodes['DIN_125_-_A_17_31'].material}
        position={[-0.16, 1.47, -1.47]}
        rotation={[1.6, -1.02, -1.54]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_32'].geometry}
        material={nodes['DIN_125_-_A_17_32'].material}
        position={[-0.25, 1.48, -1.24]}
        rotation={[-Math.PI, -1.55, -3.14]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_33'].geometry}
        material={nodes['DIN_125_-_A_17_33'].material}
        position={[-0.24, 1.48, -1.27]}
        rotation={[-Math.PI, -1.55, 0]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_34'].geometry}
        material={nodes['DIN_125_-_A_17_34'].material}
        position={[-0.24, 1.48, -1.43]}
        rotation={[0, 1.55, 3.14]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_125_-_A_17_35'].geometry}
        material={nodes['DIN_125_-_A_17_35'].material}
        position={[-0.24, 1.48, -1.47]}
        rotation={[-1.58, -0.55, 1.55]}
        userData={{ name: 'DIN 125 - A 17' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16'].geometry}
        material={nodes['DIN_934_-_M16'].material}
        position={[-0.25, 0.97, -1.08]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_1'].geometry}
        material={nodes['DIN_934_-_M16_1'].material}
        position={[-0.25, 1.17, -1.08]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_2'].geometry}
        material={nodes['DIN_934_-_M16_2'].material}
        position={[-0.25, 0.97, -0.99]}
        rotation={[0, 0, Math.PI / 2]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_3'].geometry}
        material={nodes['DIN_934_-_M16_3'].material}
        position={[-0.25, 1.17, -0.99]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_4'].geometry}
        material={nodes['DIN_934_-_M16_4'].material}
        position={[-0.16, 0.97, -0.99]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_5'].geometry}
        material={nodes['DIN_934_-_M16_5'].material}
        position={[-0.16, 1.17, -0.99]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_6'].geometry}
        material={nodes['DIN_934_-_M16_6'].material}
        position={[-0.16, 0.97, -1.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_7'].geometry}
        material={nodes['DIN_934_-_M16_7'].material}
        position={[-0.16, 1.17, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_8'].geometry}
        material={nodes['DIN_934_-_M16_8'].material}
        position={[-0.24, 1.56, -1.28]}
        rotation={[-Math.PI / 2, 0, 1.55]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_9'].geometry}
        material={nodes['DIN_934_-_M16_9'].material}
        position={[-0.24, 1.56, -1.42]}
        rotation={[Math.PI / 2, 0, -1.55]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_10'].geometry}
        material={nodes['DIN_934_-_M16_10'].material}
        position={[-0.16, 1.56, -1.27]}
        rotation={[0, 1.55, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_11'].geometry}
        material={nodes['DIN_934_-_M16_11'].material}
        position={[-0.15, 1.56, -1.41]}
        rotation={[Math.PI, -1.55, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_12'].geometry}
        material={nodes['DIN_934_-_M16_12'].material}
        position={[-0.16, 1.47, -1.28]}
        rotation={[1.57, 0, -1.55]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_13'].geometry}
        material={nodes['DIN_934_-_M16_13'].material}
        position={[-0.16, 1.47, -1.41]}
        rotation={[-1.57, 0, 1.55]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_14'].geometry}
        material={nodes['DIN_934_-_M16_14'].material}
        position={[-0.24, 1.48, -1.28]}
        rotation={[-Math.PI, -1.55, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes['DIN_934_-_M16_15'].geometry}
        material={nodes['DIN_934_-_M16_15'].material}
        position={[-0.24, 1.48, -1.42]}
        rotation={[0, 1.55, 0]}
        userData={{ name: 'DIN 934 - M16' }}
      />
      <mesh
        geometry={nodes.PlexibehXE4lter_Fermenter.geometry}
        material={nodes.PlexibehXE4lter_Fermenter.material}
        position={[-0.17, 0.55, 0.25]}
        rotation={[0, 0, 0]}
        userData={{ name: 'PlexibehXE4lter_Fermenter' }}
      />
      <mesh
        geometry={nodes.Halter_Tablet_1.geometry}
        material={nodes.Halter_Tablet_1.material}
        position={[-0.04, 0.55, 0.57]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        userData={{ name: 'Halter Tablet_1' }}
      />
      <mesh
        geometry={nodes.Kaiser_Optical.geometry}
        material={nodes.Kaiser_Optical.material}
        position={[-0.23, 0.71, 0.25]}
        rotation={[0, 0, 0]}
        userData={{ name: 'Kaiser_Optical' }}
      />
      <mesh
        geometry={nodes.Clamp50er.geometry}
        material={nodes.Clamp50er.material}
        position={[0.19, 0.53, 0.47]}
        rotation={[0, 0, 0]}
        userData={{ name: 'Clamp50er' }}
      />
    </group>
  );
}

useGLTF.preload('/M-65-341_One_Story_Exhibit_Jonas.gltf');
