/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Later modified -> replaced meshes with mesh component
*/

import Asset from '@components/asset';
import { useGLTF } from '@react-three/drei/useGLTF';
import React, { useRef } from 'react';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/model.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['CAD mat 0']} geometry={nodes.Korpus.geometry} scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]} />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.Korpus_Lampe.geometry}
        position={[0, 9.199999809265137, -3.3999998569488525]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0']}
        geometry={nodes.OneStoryExhibitBeistellsockel.geometry}
        position={[0, 0.199999988079071, 3.5]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.Korpus_Lampe_600.geometry}
        position={[0, 9.199999809265137, -0.5999999642372131]}
        rotation={[Math.PI, -1.509958025e-7, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.Schild.geometry}
        position={[-0.0499999970197678, 20.049999237060547, -4.349999904632568]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.Schild_kurz.geometry}
        position={[0.05737229809165, 20.049999237060547, 0.3499999940395355]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials.Material}
        geometry={nodes.Clamp50er.geometry}
        position={[1.5795389413833618, 9.710550308227539, -7.418252944946289]}
        rotation={[-1.554743720816145, -Math.PI / 2, 0]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.Plexibehaelter_400er.geometry}
        position={[-0.5056041479110718, 5.708792209625244, -7.397064685821533]}
        rotation={[1.565501390395454, -7.54968368e-8, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials.Material}
        geometry={nodes.Plexideckel_400mm.geometry}
        position={[-0.5, 12.399999618530273, -7.415002346038818]}
        rotation={[Math.PI / 2, 2.084434279e-7, -1.5594242608490143]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.TrustSens__1_TM371.geometry}
        position={[2.15198016166687, 17.569725036621094, -14.739999771118164]}
        rotation={[0, 0, -0.0169431638304912]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 19']}
        geometry={nodes.PMC71.geometry}
        position={[2.1196203231811523, 16.07699966430664, -10.239999771118164]}
        rotation={[-Math.PI, 1.5486574901902983, -Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.Promag_400_5W4C25.geometry}
        position={[2.1196203231811523, 15.65999984741211, -12.479999542236328]}
        rotation={[Math.PI / 2, -0.0314980058632694, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.Promass_300_8F3B25.geometry}
        position={[2.055069923400879, 11.850546836853027, -14.739999771118164]}
        rotation={[2.621770872255408, 1.5367032376745284, -1.0507261194881017]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.FMB50.geometry}
        position={[2.201040029525757, 6.407093524932861, -7.402479648590088]}
        rotation={[-2.098472095626134, -1.096293722e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.006']}
        geometry={nodes.FTL31.geometry}
        position={[2.5989999771118164, 11.59999942779541, -7.415002346038818]}
        rotation={[-0.1639737641428393, 0, -Math.PI / 2]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.PMP21.geometry}
        position={[2.7745001316070557, 10.703038215637207, -7.418479919433594]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.TM411.geometry}
        position={[2.2617998123168945, 9.701813697814941, -7.415002346038818]}
        rotation={[-3.083613358357506, 0.00000627987509, -Math.PI / 2]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.CPA871.geometry}
        position={[-0.5, 7.339613914489746, -9.64409351348877]}
        rotation={[1.832595394630332, 0.0101625666126762, -Math.PI]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.Clleitung_links_90Grad_DN25.geometry}
        position={[2.1196203231811523, 5.659999847412109, -10.239999771118164]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.Clleitung_rechts_90Grad_DN25.geometry}
        position={[2.0950539112091064, 14.210206985473633, -14.739999771118164]}
        rotation={[Math.PI / 2, -0.0169431805961051, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.Clleitung_rechts_DN25.geometry}
        position={[2.0150859355926514, 9.490885734558105, -14.739999771118164]}
        rotation={[-Math.PI / 2, 0.0169431805961051, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 30']}
        geometry={nodes.RSG45_Halter.geometry}
        position={[3.1999998092651367, 5.5, -11.38602066040039]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.FMP56.geometry}
        position={[-1.4908379316329956, 12.933000564575195, -8.226322174072266]}
        rotation={[Math.PI, -1.5606991809179265, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.FMR20.geometry}
        position={[0.3090455830097198, 12.769999504089355, -8.205853462219238]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.FMR62.geometry}
        position={[0.2908509373664856, 13.734000205993652, -6.60595703125]}
        rotation={[0, 1.5094316286830922, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.FTM50.geometry}
        position={[-1.5090327262878418, 12.637459754943848, -6.626425743103027]}
        rotation={[Math.PI, -1.5625605345047724, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.CM42.geometry}
        position={[-0.3381579220294952, 5.770516872406006, -14.46295166015625]}
        rotation={[-1.9040404282968677, 1.001940428e-7, Math.PI]}
        scale={[0.0099999997764826, 0.00999999884516, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 30']}
        geometry={nodes.CM42_Schraege.geometry}
        position={[0.3916199803352356, 5.5, -13.799999237060547]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.tmass150.geometry}
        position={[-2.0173168182373047, 8.040873527526855, -10.341775894165039]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.Prosonic_Floww_B200_9B2B50.geometry}
        position={[-2.0173168182373047, 10.688873291015625, -10.341775894165039]}
        rotation={[-3.141581044773706, -1.5656503239226998, -1.5707864160521332]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.Prowirl_100_7F2C50.geometry}
        position={[-1.9656537771224976, 15.176132202148438, -13.521615982055664]}
        rotation={[Math.PI, -1.5545521754248548, Math.PI]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 4']}
        geometry={nodes.Rohrbogen_DN50_.geometry}
        position={[-2.0172314643859863, 12.170873641967773, -10.347034454345703]}
        rotation={[Math.PI / 2, -8.91619365e-8, 1.5870421682501965]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.DN50_Rohrende_schraeg.geometry}
        position={[-1.9545577764511108, 15.178059577941895, -16.016530990600586]}
        rotation={[1.5693587688832467, 0.0882663379552518, -1.5544873720504517]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.COMPOUND001.geometry}
        position={[1.7899665832519531, 8.238078117370605, -4]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 1']}
        geometry={nodes.SOLID.geometry}
        position={[1.7899665832519531, 8.238078117370605, -4]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.COMPOUND002.geometry}
        position={[1.7899665832519531, 8.238078117370605, -4.630000114440918]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 1']}
        geometry={nodes.SOLID001.geometry}
        position={[1.7899665832519531, 8.238078117370605, -4.630000114440918]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.DM_04AVP3.geometry}
        position={[1.7899665832519531, 8.238078117370605, -4.644999980926514]}
        rotation={[0, 0, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.004']}
        geometry={nodes.DM_F2_SCHRAUBE_M4X8.geometry}
        position={[0.782466471195221, 7.898078441619873, -4.666999816894531]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.008']}
        geometry={nodes.ANTENNE.geometry}
        position={[0.9172911047935486, 8.825451850891113, -4.290104389190674]}
        rotation={[1.563814966697437, -2.969811064e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.ERDBUEGEL.geometry}
        position={[3.029966354370117, 8.038078308105469, -4.139999866485596]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.FEDERSCHEIBE.geometry}
        position={[3.029966354370117, 8.038078308105469, -4.154999732971191]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.SHELL.geometry}
        position={[3.029966354370117, 8.038078308105469, -4.174999713897705]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.SOLID002.geometry}
        position={[3.029966354370117, 8.038078308105469, -4.174999713897705]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.HalterTablet_1.geometry}
        position={[-2.450000047683716, 5.5, -14.541434288024902]}
        rotation={[-Math.PI, 1.562765028046565, -Math.PI]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.FieldXpert_1.geometry}
        position={[-2.509913682937622, 10.807453155517578, -14.68100643157959]}
        rotation={[1.5803642561308882, 0.8726262401076643, 1.5583064642628282]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes['RSG45-AA2AAAAAB1A1-Endress_HauserConsultAG--10-15-2020'].geometry}
        position={[3.0114097595214844, 6.186555862426758, -12.465458869934082]}
        rotation={[-Math.PI / 2, Math.PI / 6, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes.CM82.geometry}
        position={[2.5636801719665527, 7.892312526702881, -7.485065937042236]}
        rotation={[0, 0, -1.3089972450509704]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials.Material}
        geometry={nodes.Plexibehaelter_Fermenter.geometry}
        position={[-1.7232565879821777, 5.490013122558594, 2.4797732830047607]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <Asset
        material={materials['CAD mat 0.007']}
        geometry={nodes.Promag_100_5H1B40.geometry}
        position={[1.9175504446029663, 8.795729637145996, 4.786312103271484]}
        rotation={[0.0000028863302957, 1.5399781938370805, 1.5707933801043894]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
        id={76691}
        assetSelected={props.assetSelected}
      />
      <Asset
        material={materials['CAD mat 0.007']}
        geometry={nodes.PMP23.geometry}
        position={[1.9310983419418335, 8.698423385620117, 2.602354049682617]}
        rotation={[-1.5666776610726698, 0.5861051210142489, 3.1341464891256563]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
        id={76687}
        assetSelected={props.assetSelected}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.Clamp50_41mm_Rohr.geometry}
        position={[1.9175504446029663, 10.25058650970459, 4.786312103271484]}
        rotation={[-Math.PI / 2, -1.491033288e-7, 1.5645931656653678]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.Rohrbogen_41mm_Rohr.geometry}
        position={[1.939261794090271, 5.395730018615723, 1.2863795757293701]}
        rotation={[Math.PI / 2, -1.491033288e-7, -1.5645931656653678]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.Clamp34_30mm_Rohr.geometry}
        position={[1.9389817714691162, 8.698423385620117, 1.3315218687057495]}
        rotation={[Math.PI, 0.0062033252831626, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes['TM131-AABHBAB2HA5BFEB3CA2DA1-Endress_HauserConsultAG--10-19-202'].geometry}
        position={[-1.1232566833496094, 9.280013084411621, 2.4797732830047607]}
        rotation={[0, 1.5184460760102478, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 5']}
        geometry={nodes.Halter_442.geometry}
        position={[-0.391727089881897, 5.5, 5.674251079559326]}
        rotation={[-Math.PI, 1.509958025e-7, -Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <Asset
        material={materials['CAD mat 0.007']}
        geometry={nodes.CM44P.geometry}
        position={[-0.4126301109790802, 10.140565872192383, 6.397058963775635]}
        rotation={[-0.6981317232854003, 0, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
        id={61239}
        assetSelected={props.assetSelected}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.SHELL001.geometry}
        position={[-0.5173293352127075, 9.131490707397461, 5.400000095367432]}
        rotation={[Math.PI, -1.509958025e-7, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.COMPOUND.geometry}
        position={[-0.5173293352127075, 9.131490707397461, 5.400000095367432]}
        rotation={[Math.PI, -1.509958025e-7, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.tm311_AAC1AA0ABC1B1.geometry}
        position={[1.939261794090271, 11.855730056762695, 1.2863795757293701]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0']}
        geometry={nodes.Halterung_ACER_27zoll.geometry}
        position={[1.5, 9.199999809265137, -2]}
        rotation={[Math.PI, -1.5691920503630037, Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0']}
        geometry={nodes.Halterung_ACER_27zoll001.geometry}
        position={[-1.5, 9.199999809265137, -2]}
        rotation={[0, 1.5683683782746694, 0]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.CPA842_fuer_CPA442.geometry}
        position={[1.7168527841567993, 7.665405750274658, -7.485065937042236]}
        rotation={[0, 0, -1.3089972450509704]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.CPA842_fuer_CPA442001.geometry}
        position={[1.7269010543823242, 8.400646209716797, -7.427707195281982]}
        rotation={[0, 0, -1.3089972450509704]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_PN_16_25'].geometry}
        position={[2.1196203231811523, 5.5, -10.239999771118164]}
        rotation={[Math.PI, 7.54979021e-8, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_PN_1'].geometry}
        position={[2.1196203231811523, 15.65999984741211, -11.34000015258789]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_PN_1001'].geometry}
        position={[2.0923430919647217, 14.050230026245117, -14.739999771118164]}
        rotation={[0, 0, 1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_PN_1002'].geometry}
        position={[2.1196203231811523, 15.65999984741211, -13.479999542236328]}
        rotation={[Math.PI / 2, -0.0169431510430856, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_PN_1003'].geometry}
        position={[1.9486719369888306, 5.57144832611084, -14.739999771118164]}
        rotation={[0, 0, 1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_PN_1004'].geometry}
        position={[2.017796754837036, 9.650861740112305, -14.739999771118164]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_-_PN_25_50'].geometry}
        position={[-1.981492519378662, 15.176132202148438, -12.546744346618652]}
        rotation={[Math.PI / 2, -8.91619365e-8, 1.5870421682501965]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_-_PN_2'].geometry}
        position={[-2.0173168182373047, 11.970873832702637, -10.341775894165039]}
        rotation={[-1.3433962e-9, -0.0162456671742375, Math.PI / 2]}
        scale={[0.0099999997764826, 0.00999999884516, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_EN_1092-1_Flachflansch_fuer_Schweisstyp_01_-_PN_2001'].geometry}
        position={[-1.978992223739624, 15.17809772491455, -14.516729354858398]}
        rotation={[1.5713345453461904, -0.0437286980822738, -1.5541992060216254]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.003']}
        geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK'].geometry}
        position={[2.665001153945923, 7.462316036224365, -4.521468639373779]}
        rotation={[0.0069813169890069, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.003']}
        geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK001'].geometry}
        position={[2.3150012493133545, 7.462316036224365, -4.521468639373779]}
        rotation={[0.0069813169890069, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.003']}
        geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK002'].geometry}
        position={[1.7900011539459229, 7.462316036224365, -4.521468639373779]}
        rotation={[0.0069813169890069, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.003']}
        geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK003'].geometry}
        position={[1.2650011777877808, 7.462316036224365, -4.521468639373779]}
        rotation={[0.0069813169890069, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.003']}
        geometry={nodes['DM_CABLE-GLAND-M16-EX-BLACK004'].geometry}
        position={[0.9150012135505676, 7.462316036224365, -4.521468639373779]}
        rotation={[0.0069813169890069, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.004']}
        geometry={nodes.DM_F2_SCHRAUBE_M4X18.geometry}
        position={[0.7299664616584778, 8.728078842163086, -4.7079997062683105]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.004']}
        geometry={nodes.DM_F2_SCHRAUBE_M4X18001.geometry}
        position={[2.849966287612915, 8.728078842163086, -4.7079997062683105]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.004']}
        geometry={nodes.DM_F2_SCHRAUBE_M4X18002.geometry}
        position={[2.849966287612915, 7.748078346252441, -4.7079997062683105]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.004']}
        geometry={nodes.DM_F2_SCHRAUBE_M4X18003.geometry}
        position={[0.7299664616584778, 7.748078346252441, -4.7079997062683105]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.005']}
        geometry={nodes.DM_F2_SCHEIBE.geometry}
        position={[0.7299664616584778, 8.728078842163086, -4.699999809265137]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.005']}
        geometry={nodes.DM_F2_SCHEIBE001.geometry}
        position={[2.849966287612915, 8.728078842163086, -4.699999809265137]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.005']}
        geometry={nodes.DM_F2_SCHEIBE002.geometry}
        position={[2.849966287612915, 7.748078346252441, -4.699999809265137]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.005']}
        geometry={nodes.DM_F2_SCHEIBE003.geometry}
        position={[0.7299664616584778, 7.748078346252441, -4.699999809265137]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.005']}
        geometry={nodes.DM_F2_SCHEIBE004.geometry}
        position={[0.782466471195221, 7.898078441619873, -4.674999713897705]}
        rotation={[-Math.PI, 7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.006']}
        geometry={nodes.SWA70.geometry}
        position={[2.0359580516815186, 17.00196647644043, -9.433185577392578]}
        rotation={[0, 0.0221404932335098, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.006']}
        geometry={nodes.SWA70001.geometry}
        position={[-1.5557446479797363, 13.904533386230469, -9.006017684936523]}
        rotation={[-Math.PI, 0.0100964623544073, -Math.PI]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes['CPS11D-7AA21-Endress_HauserConsultAG--10-15-2020'].geometry}
        position={[2.7620837688446045, 8.678023338317871, -7.427707195281982]}
        rotation={[0, 0, -1.3089972450509704]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes['CPS11D-7AA21-Endress_HauserConsultAG--10-15-2020001'].geometry}
        position={[2.75203537940979, 7.942782402038574, -7.485065937042236]}
        rotation={[0, 0, -1.3089972450509704]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes['CPS11D-7AA21-Endress_HauserConsultAG--10-15-2020002'].geometry}
        position={[-1.7232565879821777, 8.835013389587402, 3.079773187637329]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.007']}
        geometry={nodes['CPS11D-7AA21-Endress_HauserConsultAG--10-15-2020003'].geometry}
        position={[-1.7232565879821777, 8.835013389587402, 1.8797733783721924]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45'].geometry}
        position={[2.4201407432556152, 5.684999942779541, -10.540519714355469]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45001'].geometry}
        position={[1.819100022315979, 5.684999942779541, -10.540519714355469]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45002'].geometry}
        position={[1.819100022315979, 5.684999942779541, -9.939478874206543]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45003'].geometry}
        position={[2.4201407432556152, 5.684999942779541, -9.939478874206543]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45004'].geometry}
        position={[2.2522835731506348, 5.7513298988342285, -15.040519714355469]}
        rotation={[0, 0, -1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45005'].geometry}
        position={[1.6513291597366333, 5.761512756347656, -15.040519714355469]}
        rotation={[1.5706733702718199, 1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45006'].geometry}
        position={[1.6513291597366333, 5.761512756347656, -14.43947982788086]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_933_-_M12_x_45007'].geometry}
        position={[2.2522835731506348, 5.7513298988342285, -14.43947982788086]}
        rotation={[-1.5706733702718199, -1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13'].geometry}
        position={[2.4201407432556152, 5.684999942779541, -10.540519714355469]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13001'].geometry}
        position={[1.819100022315979, 5.684999942779541, -10.540519714355469]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13002'].geometry}
        position={[1.819100022315979, 5.684999942779541, -9.939478874206543]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13003'].geometry}
        position={[2.4201407432556152, 5.684999942779541, -9.939478874206543]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13004'].geometry}
        position={[2.2522835731506348, 5.7513298988342285, -15.040519714355469]}
        rotation={[0, 0, -1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13005'].geometry}
        position={[1.6513291597366333, 5.761512756347656, -15.040519714355469]}
        rotation={[1.5706733702718199, 1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13006'].geometry}
        position={[1.6513291597366333, 5.761512756347656, -14.43947982788086]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13007'].geometry}
        position={[2.2522835731506348, 5.7513298988342285, -14.43947982788086]}
        rotation={[-1.5706733702718199, -1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13008'].geometry}
        position={[2.3959546089172363, 14.23011302947998, -15.040519714355469]}
        rotation={[0, 0, -1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13009'].geometry}
        position={[2.3803257942199707, 13.84032154083252, -15.04927921295166]}
        rotation={[0, 0, 1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13010'].geometry}
        position={[1.7950003147125244, 14.240296363830566, -15.040519714355469]}
        rotation={[1.5706733702718199, 1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13011'].geometry}
        position={[1.7796343564987183, 13.850500106811523, -15.03149700164795]}
        rotation={[1.5709196861190513, 1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13012'].geometry}
        position={[1.7950003147125244, 14.240296363830566, -14.43947982788086]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13013'].geometry}
        position={[1.7974141836166382, 13.850198745727539, -14.430720329284668]}
        rotation={[Math.PI, 7.54870225e-8, -1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13014'].geometry}
        position={[2.3959546089172363, 14.23011302947998, -14.43947982788086]}
        rotation={[-1.5706733702718199, -1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13015'].geometry}
        position={[2.3981056213378906, 13.840020179748535, -14.448501586914062]}
        rotation={[-1.5709196861190513, -1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13016'].geometry}
        position={[2.312725782394409, 9.850894927978516, -15.04927921295166]}
        rotation={[0, 0, -1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13017'].geometry}
        position={[2.3151397705078125, 9.460797309875488, -15.040519714355469]}
        rotation={[0, 0, 1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13018'].geometry}
        position={[2.330505609512329, 9.850592613220215, -14.448501586914062]}
        rotation={[-1.5706733702718199, -1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13019'].geometry}
        position={[2.3151397705078125, 9.460797309875488, -14.43947982788086]}
        rotation={[-1.5709196861190513, -1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13020'].geometry}
        position={[1.7298142910003662, 9.860772132873535, -14.430720329284668]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13021'].geometry}
        position={[1.7141852378845215, 9.470980644226074, -14.43947982788086]}
        rotation={[Math.PI, 7.5486878e-8, -1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13022'].geometry}
        position={[1.7120344638824463, 9.861072540283203, -15.03149700164795]}
        rotation={[1.5706733702718199, 1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13023'].geometry}
        position={[1.7141852378845215, 9.470980644226074, -15.040519714355469]}
        rotation={[1.5709196861190513, 1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13024'].geometry}
        position={[2.415006160736084, 15.35443115234375, -13.664999961853027]}
        rotation={[0, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13025'].geometry}
        position={[2.410527229309082, 15.350164413452148, -13.274999618530273]}
        rotation={[0, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13026'].geometry}
        position={[1.814051628112793, 15.36461353302002, -13.664999961853027]}
        rotation={[-Math.PI / 2, 1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13027'].geometry}
        position={[1.8097847700119019, 15.36909294128418, -13.274999618530273]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13028'].geometry}
        position={[1.8242346048355103, 15.965568542480469, -13.664999961853027]}
        rotation={[Math.PI, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13029'].geometry}
        position={[1.828713297843933, 15.96983528137207, -13.274999618530273]}
        rotation={[-Math.PI, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13030'].geometry}
        position={[2.425189256668091, 15.955385208129883, -13.664999961853027]}
        rotation={[Math.PI / 2, 1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13031'].geometry}
        position={[2.4294559955596924, 15.950906753540039, -13.274999618530273]}
        rotation={[-Math.PI / 2, -1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13032'].geometry}
        position={[2.4201407432556152, 15.359479904174805, -11.3149995803833]}
        rotation={[0, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13033'].geometry}
        position={[2.410527229309082, 15.350164413452148, -11.684999465942383]}
        rotation={[0, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13034'].geometry}
        position={[2.4201407432556152, 15.960519790649414, -11.3149995803833]}
        rotation={[-Math.PI / 2, -1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13035'].geometry}
        position={[2.4294559955596924, 15.950906753540039, -11.684999465942383]}
        rotation={[Math.PI / 2, 1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13036'].geometry}
        position={[1.819100022315979, 15.960519790649414, -11.3149995803833]}
        rotation={[Math.PI, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13037'].geometry}
        position={[1.828713297843933, 15.96983528137207, -11.684999465942383]}
        rotation={[-Math.PI, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13038'].geometry}
        position={[1.819100022315979, 15.359479904174805, -11.3149995803833]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13039'].geometry}
        position={[1.8097847700119019, 15.36909294128418, -11.684999465942383]}
        rotation={[-Math.PI / 2, 1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55'].geometry}
        position={[2.3959546089172363, 14.23011302947998, -15.040519714355469]}
        rotation={[0, 0, -1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55001'].geometry}
        position={[1.7950003147125244, 14.240296363830566, -15.040519714355469]}
        rotation={[1.5706733702718199, 1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55002'].geometry}
        position={[1.7950003147125244, 14.240296363830566, -14.43947982788086]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55003'].geometry}
        position={[2.3959546089172363, 14.23011302947998, -14.43947982788086]}
        rotation={[-1.5706733702718199, -1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55004'].geometry}
        position={[2.3151397705078125, 9.460797309875488, -15.040519714355469]}
        rotation={[0, 0, 1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55005'].geometry}
        position={[2.3151397705078125, 9.460797309875488, -14.43947982788086]}
        rotation={[-1.5709196861190513, -1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55006'].geometry}
        position={[1.7141852378845215, 9.470980644226074, -14.43947982788086]}
        rotation={[Math.PI, 7.5486878e-8, -1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55007'].geometry}
        position={[1.7141852378845215, 9.470980644226074, -15.040519714355469]}
        rotation={[1.5709196861190513, 1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55008'].geometry}
        position={[2.415006160736084, 15.35443115234375, -13.664999961853027]}
        rotation={[0, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55009'].geometry}
        position={[1.814051628112793, 15.36461353302002, -13.664999961853027]}
        rotation={[-Math.PI / 2, 1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55010'].geometry}
        position={[1.8242346048355103, 15.965568542480469, -13.664999961853027]}
        rotation={[Math.PI, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55011'].geometry}
        position={[2.425189256668091, 15.955385208129883, -13.664999961853027]}
        rotation={[Math.PI / 2, 1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55012'].geometry}
        position={[2.4201407432556152, 15.359479904174805, -11.3149995803833]}
        rotation={[0, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55013'].geometry}
        position={[2.4201407432556152, 15.960519790649414, -11.3149995803833]}
        rotation={[-Math.PI / 2, -1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55014'].geometry}
        position={[1.819100022315979, 15.960519790649414, -11.3149995803833]}
        rotation={[Math.PI, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_125_-_A_13DIN_933_-_M12__x_55015'].geometry}
        position={[1.819100022315979, 15.359479904174805, -11.3149995803833]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5'].geometry}
        position={[2.378631591796875, 13.740335464477539, -15.04927921295166]}
        rotation={[0, 0, 1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5001'].geometry}
        position={[1.7779401540756226, 13.75051498413086, -15.03149700164795]}
        rotation={[1.5709196861190513, 1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5002'].geometry}
        position={[1.7957199811935425, 13.750213623046875, -14.430720329284668]}
        rotation={[Math.PI, 7.54870225e-8, -1.5538531743196207]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5003'].geometry}
        position={[2.396411418914795, 13.740035057067871, -14.448501586914062]}
        rotation={[-1.5709196861190513, -1.55385328843467, -0.0001231574162628]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5004'].geometry}
        position={[2.314419984817505, 9.95088005065918, -15.04927921295166]}
        rotation={[0, 0, -1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5005'].geometry}
        position={[2.332199811935425, 9.950578689575195, -14.448501586914062]}
        rotation={[-1.5706733702718199, -1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5006'].geometry}
        position={[1.731508493423462, 9.9607572555542, -14.430720329284668]}
        rotation={[Math.PI, -7.67768223e-8, 1.5877394772735287]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5007'].geometry}
        position={[1.7137285470962524, 9.961058616638184, -15.03149700164795]}
        rotation={[1.5706733702718199, 1.5538551220338932, -3.141467781090049]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5008'].geometry}
        position={[2.410527229309082, 15.350164413452148, -13.174999237060547]}
        rotation={[0, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5009'].geometry}
        position={[1.8097847700119019, 15.36909294128418, -13.174999237060547]}
        rotation={[Math.PI / 2, -1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5010'].geometry}
        position={[1.828713297843933, 15.96983528137207, -13.174999237060547]}
        rotation={[-Math.PI, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5011'].geometry}
        position={[2.4294559955596924, 15.950906753540039, -13.174999237060547]}
        rotation={[-Math.PI / 2, -1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5012'].geometry}
        position={[2.410527229309082, 15.350164413452148, -11.78499984741211]}
        rotation={[0, -1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5013'].geometry}
        position={[2.4294559955596924, 15.950906753540039, -11.78499984741211]}
        rotation={[Math.PI / 2, 1.192092896e-7, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5014'].geometry}
        position={[1.828713297843933, 15.96983528137207, -11.78499984741211]}
        rotation={[-Math.PI, 1.5705346837209222, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes['DIN_934_-_M12_x_1,5015'].geometry}
        position={[1.8097847700119019, 15.36909294128418, -11.78499984741211]}
        rotation={[-Math.PI / 2, 1.192092896e-7, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55.geometry}
        position={[-2.459258556365967, 5.800873279571533, -10.78371810913086]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55001.geometry}
        position={[-2.459258556365967, 9.28087329864502, -10.78371810913086]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55002.geometry}
        position={[-2.4520208835601807, 12.200873374938965, -10.790839195251465]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55003.geometry}
        position={[-2.459258556365967, 5.800873279571533, -9.899834632873535]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55004.geometry}
        position={[-2.459258556365967, 9.28087329864502, -9.899834632873535]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55005.geometry}
        position={[-2.4663796424865723, 12.200873374938965, -9.907072067260742]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55006.geometry}
        position={[-1.5753751993179321, 5.800873279571533, -9.899834632873535]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55007.geometry}
        position={[-1.5753751993179321, 9.28087329864502, -9.899834632873535]}
        rotation={[-Math.PI, -7.54979021e-8, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55008.geometry}
        position={[-1.5826127529144287, 12.200873374938965, -9.89271354675293]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55009.geometry}
        position={[-1.5753751993179321, 5.800873279571533, -10.78371810913086]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55010.geometry}
        position={[-1.5753751993179321, 9.28087329864502, -10.78371810913086]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55011.geometry}
        position={[-1.5682542324066162, 12.200873374938965, -10.776480674743652]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55012.geometry}
        position={[-2.427112340927124, 15.618073463439941, -12.323953628540039]}
        rotation={[0, 1.5545524283426995, 0]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55013.geometry}
        position={[-2.397317886352539, 15.638895034790039, -14.753785133361816]}
        rotation={[Math.PI, -1.5542154153757883, -3.1414073232179835]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55014.geometry}
        position={[-1.5759648084640503, 15.5902099609375, -12.309833526611328]}
        rotation={[1.5709449331050334, 0.0000023482309537, -1.554027940244967]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55015.geometry}
        position={[-1.5144010782241821, 15.600253105163574, -14.7391357421875]}
        rotation={[-1.5709836064481875, 0.0000031323785947, -1.587377894522867]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55016.geometry}
        position={[-1.6038269996643066, 14.738945007324219, -12.310136795043945]}
        rotation={[3.141583728055835, -1.5538881778273115, 0.0003655348161727]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55017.geometry}
        position={[-1.5530396699905396, 14.717215538024902, -14.739611625671387]}
        rotation={[-0.0000018953848885, 1.554215500137001, 3.1414072392611367]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55018.geometry}
        position={[-2.45497465133667, 14.76680850982666, -12.32425594329834]}
        rotation={[-1.5713193327191795, 0.0000083998703567, 1.5544021523743288]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_933_M16_x_55019.geometry}
        position={[-2.4359564781188965, 14.755855560302734, -14.754260063171387]}
        rotation={[1.5706092096048845, -0.0000029521106235, 1.5873781349099247]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17.geometry}
        position={[-2.459258556365967, 5.770873069763184, -10.78371810913086]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17001.geometry}
        position={[-2.4569778442382812, 9.7108736038208, -10.78598690032959]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17002.geometry}
        position={[-2.459258556365967, 9.310873031616211, -10.78371810913086]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17003.geometry}
        position={[-2.4569778442382812, 11.7708740234375, -10.78598690032959]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17004.geometry}
        position={[-2.4520208835601807, 12.170873641967773, -10.790839195251465]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17005.geometry}
        position={[-2.459258556365967, 5.770873069763184, -9.899834632873535]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17006.geometry}
        position={[-2.4615275859832764, 9.7108736038208, -9.902115821838379]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17007.geometry}
        position={[-2.459258556365967, 9.310873031616211, -9.899834632873535]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17008.geometry}
        position={[-2.4615275859832764, 11.7708740234375, -9.902115821838379]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17009.geometry}
        position={[-2.4663796424865723, 12.170873641967773, -9.907072067260742]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17010.geometry}
        position={[-1.5753751993179321, 5.770873069763184, -9.899834632873535]}
        rotation={[-Math.PI, -7.54979021e-8, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17011.geometry}
        position={[-1.5776559114456177, 9.7108736038208, -9.897565841674805]}
        rotation={[-Math.PI, -7.54979021e-8, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17012.geometry}
        position={[-1.5753751993179321, 9.310873031616211, -9.899834632873535]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17013.geometry}
        position={[-1.5776559114456177, 11.7708740234375, -9.897565841674805]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17014.geometry}
        position={[-1.5826127529144287, 12.170873641967773, -9.89271354675293]}
        rotation={[-Math.PI, -7.54979021e-8, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17015.geometry}
        position={[-1.5753751993179321, 5.770873069763184, -10.78371810913086]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17016.geometry}
        position={[-1.573106050491333, 9.7108736038208, -10.781437873840332]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17017.geometry}
        position={[-1.5753751993179321, 9.310873031616211, -10.78371810913086]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17018.geometry}
        position={[-1.573106050491333, 11.7708740234375, -10.781437873840332]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17019.geometry}
        position={[-1.5682542324066162, 12.170873641967773, -10.776480674743652]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17020.geometry}
        position={[-2.4266250133514404, 15.618073463439941, -12.353949546813965]}
        rotation={[Math.PI, -1.5545521754248548, Math.PI]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17021.geometry}
        position={[-2.4204518795013428, 15.618073463439941, -12.73390007019043]}
        rotation={[0, 1.5545524283426995, 0]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17022.geometry}
        position={[-2.394622325897217, 15.618073463439941, -14.323689460754395]}
        rotation={[-0.0000046468330725, 1.5545523440371887, -Math.PI]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17023.geometry}
        position={[-2.397815227508545, 15.638899803161621, -14.723788261413574]}
        rotation={[1.560362391903695, 0.5534878317393004, -1.5513047526787755]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17024.geometry}
        position={[-1.575461745262146, 15.590214729309082, -12.33983039855957]}
        rotation={[-1.5706479571136553, -0.0000022891769511, -1.5875656641529348]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17025.geometry}
        position={[-1.5690898895263672, 15.59027099609375, -12.719776153564453]}
        rotation={[1.5709449331050334, 0.0000023482309537, -1.554027940244967]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17026.geometry}
        position={[-1.5424288511276245, 15.590507507324219, -14.309553146362305]}
        rotation={[1.5709448760046179, 0.0000027058949215, 1.5875654277402642]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17027.geometry}
        position={[-1.5148985385894775, 15.600258827209473, -14.709139823913574]}
        rotation={[1.5974307960086995, -1.0170011496684033, -1.5392646312882456]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17028.geometry}
        position={[-1.603319525718689, 14.738933563232422, -12.340132713317871]}
        rotation={[-0.0000074316060637, 1.5538780414164546, 3.1412256156239895]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17029.geometry}
        position={[-1.5968912839889526, 14.738792419433594, -12.720077514648438]}
        rotation={[3.141583728055835, -1.5538881778273115, 0.0003655348161727]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17030.geometry}
        position={[-1.5699939727783203, 14.73819637298584, -14.309850692749023]}
        rotation={[Math.PI, -1.5538778726952642, -3.1412256351546173]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17031.geometry}
        position={[-1.5535370111465454, 14.717220306396484, -14.709614753723145]}
        rotation={[-1.5812308268034647, -0.5534880022045578, 1.5513048981353543]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17032.geometry}
        position={[-2.4544827938079834, 14.766793251037598, -12.354252815246582]}
        rotation={[1.5702731354241055, -0.0000085209987689, 1.5871904339581666]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17033.geometry}
        position={[-2.4482531547546387, 14.766594886779785, -12.734201431274414]}
        rotation={[-1.5713193327191795, 0.0000083998703567, 1.5544021523743288]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17034.geometry}
        position={[-2.422187566757202, 14.765762329101562, -14.32398796081543]}
        rotation={[-1.5713192105520182, 0.0000087565090433, -1.5871905539874367]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_125_A_17035.geometry}
        position={[-2.4364540576934814, 14.755861282348633, -14.724263191223145]}
        rotation={[-1.5441618027053396, 1.0170012040376553, 1.539264015524203]}
        scale={[0.00999999884516, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2.geometry}
        position={[-2.4569778442382812, 9.740873336791992, -10.78598690032959]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2001.geometry}
        position={[-2.4569778442382812, 11.740873336791992, -10.78598690032959]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2002.geometry}
        position={[-2.4615275859832764, 9.740873336791992, -9.902115821838379]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2003.geometry}
        position={[-2.4615275859832764, 11.740873336791992, -9.902115821838379]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2004.geometry}
        position={[-1.5776559114456177, 9.740873336791992, -9.897565841674805]}
        rotation={[-Math.PI, -7.54979021e-8, -Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2005.geometry}
        position={[-1.5776559114456177, 11.740873336791992, -9.897565841674805]}
        rotation={[Math.PI, -7.54979021e-8, Math.PI / 2]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2006.geometry}
        position={[-1.573106050491333, 9.740873336791992, -10.781437873840332]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2007.geometry}
        position={[-1.573106050491333, 11.740873336791992, -10.781437873840332]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2008.geometry}
        position={[-2.419964551925659, 15.618073463439941, -12.763895988464355]}
        rotation={[0, 1.5545524283426995, 0]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2009.geometry}
        position={[-2.397221565246582, 15.618073463439941, -14.163710594177246]}
        rotation={[Math.PI, -1.5545524283426995, -0.0000046468828323]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2010.geometry}
        position={[-1.568586826324463, 15.590275764465332, -12.749773025512695]}
        rotation={[1.5709449331050334, 0.0000023482309537, -1.554027940244967]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2011.geometry}
        position={[-1.5451117753982544, 15.590482711791992, -14.149575233459473]}
        rotation={[-1.570647775793054, -0.0000026467434431, 1.554027940271829]}
        scale={[0.00999999884516, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2012.geometry}
        position={[-1.596383810043335, 14.73878002166748, -12.75007438659668]}
        rotation={[3.141583728055835, -1.5538881778273115, 0.0003655348161727]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2013.geometry}
        position={[-1.5727007389068604, 14.738256454467773, -14.149872779846191]}
        rotation={[-0.0000074316991373, 1.5538881778227673, -0.0003670286035023]}
        scale={[0.00999999884516, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2014.geometry}
        position={[-2.4477615356445312, 14.766579627990723, -12.76419734954834]}
        rotation={[-1.5713193327191795, 0.0000083998703567, 1.5544021523743288]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.002']}
        geometry={nodes.DIN_934_M16_x_2015.geometry}
        position={[-2.4248106479644775, 14.765847206115723, -14.164008140563965]}
        rotation={[1.57027349598833, -0.0000087284260105, -1.5544023332188368]}
        scale={[0.0099999997764826, 0.00999999884516, 0.0099999997764826]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.Bildschrim_22Zoll.geometry}
        position={[2.2272655963897705, 10.89556884765625, -2.005441665649414]}
        rotation={[-1.5691686652115422, Math.PI / 4, 1.5691686652115422]}
        scale={[0.0099999997764826, 0.0099999997764826, 0.00999999884516]}
      />
      <mesh
        material={materials['CAD mat 0.001']}
        geometry={nodes.Bildschrim_22Zoll001.geometry}
        position={[-2.3200087547302246, 10.700434684753418, -1.8083187341690063]}
        rotation={[-1.573229974783312, -Math.PI / 4, -1.5732300204027614]}
        scale={[0.0099999997764826, 0.00999999884516, 0.00999999884516]}
      />
    </group>
  );
}

useGLTF.preload('/model.glb');
